### ISSUE TITLE
Add BakeIt Options to a lot of LB Visualization Components

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/ladybug#104]
@chriswmackey did not put this in any of his components and he should :)

**Comment by chriswmackey** [comment]
I just had a bran blast the other day that gave me the last piece of what I needed to respond to @mostaphaRoudsari 's initial comment on this issue.

As stated previously, we presently have no official workflow for taking Ladybug graphics and exporting them to vector-based programs like illustrator and yet I know by talking to a lot of people that there is a really high demand for this workflow (moreso than the workflow where @mostaphaRoudsari has been using the bakeIt option to record results of parametric runs).  There are a number of things that need to be different in the "usual" baking operation to make this workflow possible:

1) All text should be put in the Rhino scene as actual text objects (as previously mentioned)
2) All colored meshes should be exported as colored hatches (since illustrator does not treat meshes as solid filled surfaces)
3) If possible, it would be nice to have the different types of outputs baked to different layers to make it easy to select in programs like illustrator.

I just figured out how to convert colored meshes to colored hatches yesterday and so I am going to aim to include this functionality in the next stable release.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey Thanks. All sounds good to me. Back to mesh>hatch as far as changing meshes to hatches doesn't add dramatically to the size of the file I'm cool with this.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

It's a really quick operation and does not increase the file size much as far as my experiments yesterday showed.

Also, I will still leave in an option for you to get colored meshes with the bakeit option but it's role will be downplayed.  The bakeIt input will basically be changed to an integer input where:
0 / False - Nothing is baked
1 / True -  Geometry for Illustrator export is baked (with colored hatches)
2 - Geometry for recording parametric runs is baked (with colored meshes)

This new hatch baking feature will also include a component that is able to take any one of our Ladybug colored meshes and bake them into the Rhino scene as a hatch (in case you want to bake after an anlysis is run).

-Chris

**Comment by chriswmackey** [comment]
This has been implemented on all Ladybug visual components.  Both the option for hatches and meshes are available as previously advertised.  I will try to implement the same for Honeybee components at some point.  As such, I am moving the issue over to HB and closing out the one here.
