### ISSUE TITLE
Add in Option to Turn Psych Chart into Molier hx Diagram

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/ladybug#119]
As per this discussion:
http://www.grasshopper3d.com/group/ladybug/forum/topics/legend-facing-camera?commentId=2985220%3AComment%3A1209416&xg_source=msg_com_gr_forum

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I was wondering if you had any suggestions for how to implement this.  I could just go with the standard adding of a simple boolean option to the component but the psych chart is already the largest component that we have.  If we can't think of any elegant ways to implement it, I will just do the boolean but I figured that I would ask.
-Chris

**Comment by mostaphaRoudsari** [comment]
Hey @chriswmackey! I wish we could overwrite menu items for the component so we could use the menu to change the type. For now I think we have to go with an extra input.
I asked for this before but I'm not sure if it will happen (https://github.com/mcneel/ghpython/issues/43#issuecomment-14632692).

cc: @piac here is a case that you can see having access to menu item can clearly help us.

**Comment by chriswmackey** [comment]
It is done!
![molierhximplemented](https://cloud.githubusercontent.com/assets/5567574/8611729/ad3139f6-2693-11e5-8dbe-ef00a7440353.PNG)
