### ISSUE TITLE
Figure Out How to Cancel a Parallel Function With ESC

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/ladybug#121]
I just realized that my parallel functions cannot use the usual ESC key functionality inside a "for" loop that I have built into a number of my components.  This is bad as the parallel processes are usually the long ones that I really need to cancel if they are not working out.  If anyone has good documentation for how to cancel a parallel process run with tasks.Parallel.ForEach, please let me know.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey I would just check radiation component in Ladybug. It has a very similar situation and as far as I know it works fine.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
The Esc functionality that you implemented on parallel radiation only cancels the for loop of the sky patches.  Not the actual parallel process of running each of the test points.  It helps in your case because you have a for loop in a for loop but you are still waiting for each of the points to be cancelled when you hold down Esc.  Also, when you don't have a for loop in a for loop, as I have on the solar temperature adjustor, the Esc key really doesn't help at all.
-Chris

**Comment by mostaphaRoudsari** [comment]
I see. Then you can put it under a while and your condition.
While (no one presses esc):
         your multi-thread stuff

**Comment by chriswmackey** [comment]
After trying a bunch of different arrangements of code, I finally figured out the best way to do this.  The try/except loop has to go completely around everything, including both the function being run in parallel and the code that calls the function.  The false assertion needs to be inside the function being run in parallel.  Unfortunately for the climate maps, each step of the loop can sometimes take a while so you might have to hold down esc for a few seconds before the false assertion kicks in but it is working as best it can now now.
