### ISSUE TITLE
mannequin component error

### ISSUE THREAD

**Issue by agusHariyadi** [mostaphaRoudsari/ladybug#123]
@chriswmackey , How can I resolved this problem? I have use the last updated files.
thank you..
![mannequin](https://cloud.githubusercontent.com/assets/6168707/5970530/eae6d0f2-a877-11e4-85e7-ea7f854185db.JPG)

**Comment by chriswmackey** [comment]
@agusHariyadi ,
Thank you so much for finding this.  I somehow fixed this issue on all the other components with a legend but I forgot to fix this one.
I just uploaded a fixed version to the github.
![comfort maneeequin fixed](https://cloud.githubusercontent.com/assets/5567574/5971014/a081b2e2-a80a-11e4-9dfa-3ac93a472edd.PNG)
Thanks again,
-Chris
