### ISSUE TITLE
Small spelling mistake - Outdoor Comfort Calculator

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/ladybug#124]
In the scale description there is written -3 instead of 3 for extreme hot
See line 291 og 296 in the script.
How could I fix it here, so I could do it instead of you guys when it is as small as this one?

**Comment by chriswmackey** [comment]
@arkdanielnielsen ,
Thanks for reporting.  I just fixed it.
![image](https://cloud.githubusercontent.com/assets/5567574/5973603/5f40ebc6-a838-11e4-8b3d-1550cb876ae0.png)
-Chris

**Comment by mostaphaRoudsari** [comment]
Hi @arkdanielnielsen, Back to your question, here is the brief description on how you can do it yourself and send a pull request:
1. You need to fork Ladybug and clone it on your system (You need to have a copy of Ladybug files on your system that is connected to github repository).
2. You can fix the code inside the component which I assume you already know how.
3. update the date of the component to match the day inside the component
![image](https://cloud.githubusercontent.com/assets/2915573/5988313/2b240886-a929-11e4-9f1b-d020c0a88587.png)
4. use Ladybug_Export ladybug component to export new component to the location that you cloned ladybug (number 1)
![image](https://cloud.githubusercontent.com/assets/2915573/5989838/46f1c08c-a963-11e4-9f35-79750925e6b1.png)

5. Use github application to push it back to your github repo. It should be a .py file and .ghuser file for each component.

![image](https://cloud.githubusercontent.com/assets/2915573/5989852/bc94f2f0-a963-11e4-899f-7b7a9d81b963.png)

6. Send us a pull request and we can merge it in.

I know it can be confusing once you want to get started but it is pretty straight forward if you do it a couple of times. I assume @ayezioro can confirm this as he has been through the same process while ago.

**Comment by ayezioro** [comment]
It was a while ago, but i remember doing as Mostapha described.
-A.

On Sat, Jan 31, 2015 at 11:12 PM, Mostapha Sadeghipour Roudsari <
notifications@github.com> wrote:

> Hi @arkdanielnielsen <https://github.com/arkdanielnielsen>, Back to your
> question, here is the brief description on how you can do it yourself and
> send a pull request:
> 1. You need to fork Ladybug and clone it on your system (You need to have
> a copy of Ladybug files on your system that is connected to github
> repository).
> 2. You can fix the code inside the component which I assume you already
> know how.
> 3. update the date of the component to match the day inside the component
> [image: image]
> <https://cloud.githubusercontent.com/assets/2915573/5988313/2b240886-a929-11e4-9f1b-d020c0a88587.png>
> 4. use Ladybug_Export ladybug component to export new component to the
> location that you cloned ladybug (number 1)
> [image: image]
> <https://cloud.githubusercontent.com/assets/2915573/5989838/46f1c08c-a963-11e4-9f35-79750925e6b1.png>
>
>    1. Use github application to push it back to your github repo. It
>    should be a .py file and .ghuser file for each component.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/2915573/5989852/bc94f2f0-a963-11e4-899f-7b7a9d81b963.png>
>
>    1. Send us a pull request and we can merge it in.
>
> I know it can be confusing once you want to get started but it is pretty
> straight forward if you do it a couple of times. I assume @ayezioro
> <https://github.com/ayezioro> can confirm this as he has been through the
> same process while ago.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mostaphaRoudsari/ladybug/issues/124#issuecomment-72336908>
> .
>



-- 


Abraham Yezioro, Arch, D.Sc.
Faculty of Architecture and Town Planning
Technion - IIT
Haifa, 32000. Israel
Tel: 972-4-8294044, Fax: 972-4-8294617
Cel: 972-544-604484

**Comment by chriswmackey** [comment]
@arkdanielnielsen ,
I'm sorry that I completely missed your question.  Somehow I only saw the issue and not that you wanted to solve it (when I have a hammer, everything looks like a nail to me).  Let me know if you have any questions on the workflow @mostaphaRoudsari described.
-Chris
