### ISSUE TITLE
Psychrometric chart doesn't show the strategy name if it is not effective

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#126]
I assume you want to see the name still there but it is effective for 0% of the time.

![image](https://cloud.githubusercontent.com/assets/2915573/6004454/dc55f51c-aad0-11e4-8253-e87e98fec698.png)

Here is the file: https://www.dropbox.com/s/7yir1ngs3w254bn/PSY_Chart.gh?dl=0

**Comment by chriswmackey** [comment]
@mostaphaRoudasri
This is not a bug but something I was doing intentionally since the strategy is irrelevant if there is no upper limit of humidity for the comfort polygon. I can add in a zero and a name there but there will be no polygon would be generated. Does this sound good?

**Comment by mostaphaRoudsari** [comment]
@chriswmackey what about a warning? so you can also teach users about this fact?

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Sounds good.  I will put one in now.
-Chris

**Comment by chriswmackey** [comment]
Done
![psych chart fixed](https://cloud.githubusercontent.com/assets/5567574/6011842/5aa16ca2-ab0e-11e4-8997-349e5a15aaaa.PNG)
