### ISSUE TITLE
'Ladybug_North':  '_centerPt_' input not reading a point unless manually changing the type hint

### ISSUE THREAD

**Issue by agamas** [mostaphaRoudsari/ladybug#127]
![ladybugnorth_centerpt_notworking](https://cloud.githubusercontent.com/assets/10874612/6085107/b4a2e606-adeb-11e4-8f2c-2a5a0899e943.png)

I already have an object with the fix, or at least a possible fix since there were no changes to the code. The solution was just right-clicking on top of the '_centerPt_' input and setting the type hint to Pt. In case this solution was good enough to be the final fix to the issue, what would be the way to share the file (or other files for these matters)?
Thanks,
Alejandro

**Comment by mostaphaRoudsari** [comment]
Thanks @agamas. It is fixed now 531a9fa3bf4c858b5bafd48090690a3cdde530aa
