### ISSUE TITLE
Wish - a convertion component from kWh/m2 to Wh/m2

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/ladybug#130]
Maybe there is already a method for this I have overlooked?
I have tried to edit one of the components to convert from kWh/m2 to Wh/m2. 
Slowly... I mean really slowly I am getting into scripting. I works, but it does not have the right input/output text. At the moment I could not figure out how to change the input/output text.
https://www.dropbox.com/s/zpejqkv4p6mx6zs/Ladybug_Wish_AverageData.gh?dl=0
![ladybug_wish_averagedata-04](https://cloud.githubusercontent.com/assets/7299731/6107157/801ff840-b068-11e4-9aa0-8c6390b7d62d.JPG)

**Comment by chriswmackey** [comment]
@arkdanielnielsen ,
This is looking good.  If you right click on the input/output, you can change the name of it at the top of the drop-down list.  Make sure that you change the name of the variable inside the component to match the changes that you make on the names outside the component.  Also, change the descriptions of the inputs/outputs at the top of the code inside the component.  With that, I would say that you've got your first official component under your belt.
-Chris

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen @chriswmackey I think It can be a boolean option for the component that we already have.

@chriswmackey aren't you already checking for the units (kwh vs wh) inside the component?

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Which component do you mean?  If it's the color zones component, the component always uses the unit system of the lugged in data (whether its C or F or kWh or % or PMV, etc).  Are you saying that you want me to put in a boolean just for energy cases?
-Chris

**Comment by arkdanielnielsen** [comment]
Alright, I have manage to edit the "wh to btu" component so it works convert kwh to wh instead... I think it works in all cases. I have not manage to change image on the component. How do you do that? 
Link:
https://www.dropbox.com/s/88rgy5zxc7tix93/convert_kWh2Wh_01.gh?dl=0

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen first of all congratulations! You can just drag and drop an image on top of component and it will be embedded into the component.

@chriswmackey I was talking about conversion component. Should we have these two conversions in the same component?

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

Ah.  That makes much more sense.  I think putting the two converters together into one component is a good idea.  It should accept kWh and put out either BTU or Wh depending on the boolean value.  @arkdanielnielsen , what do you think and would you be able to work this into your current version?

Also, that image drag-and-drop trick is amazing.  I had been creating a new user object each time and then deleting it after dragging it onto my canvas.  I wonder how many shortcuts there are that I still don't know.

-Chris

**Comment by arkdanielnielsen** [comment]
I think it would be better with separated components. To have less boolean's you need to turn on/off, and in general have less components on the canvas. Further, often you would only use either Wh or BTU.

**Comment by arkdanielnielsen** [comment]
Is it possible to get access to the icon images that is used to the other conversion components? I think it would be easier to just edit one of them to make a kWh2Wh :)

**Comment by chriswmackey** [comment]
@arkdanielnielsen ,
I have just shared a dropbox link with you to the illustrator file containing all of the LB + HB icons.  I'm ok with 2 components for the sake of consistency with the other converters.  However, because we have so many of these converters, I am going to insist that this one only be in the drop-down of the extra tab. @mostaphaRoudsari , what do you think?
-Chris

**Comment by arkdanielnielsen** [comment]
Thanks @chriswmackey 
I have followed your video @mostaphaRoudsari but I am not sure how it works after I have uploaded the component at my github?: https://github.com/arkdanielnielsen/Ladybug_adn
Is it then up to you guys to prove it and then merge it to the "real" ladybug?

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen great to see you that you have your first component ready! You need to "fork" Ladybug first and then commit your new component to the fork and send us a "pull request". Then we can merge it into the "master" branch.
I know I used so many buzz words here but if you check online there should be so many examples that shows how to do it.

**Comment by mostaphaRoudsari** [comment]
and I agree with @chriswmackey that we should keep it in the dropdown since we have so many of this. I think at some point we will merge both wh conversations but since this is @arkdanielnielsen's first component we can take it easy. Welcome to the developers team! :tada:

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen did you figure out how to do this?

**Comment by chriswmackey** [comment]
I implemented this a while back:
https://github.com/mostaphaRoudsari/ladybug/commit/e448f0662ef61e7723b90eca1c4347878a20adc5
