### ISSUE TITLE
LB_windRose + analysisPeriod Title issue

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#135]
Hi,
Using the conditionalStatment in the windRose gives a "wrong" title when defining an analysis period different than the whole year.
The percentage of hours from the condition is extracted from the whole year hours (8760) instead of the analysis period hours. It is nice having the % from the year, but nicer also from the desired period.
Thanks,
-A.

**Comment by chriswmackey** [comment]
Thanks for finding the bug @ayezioro. I was the last one to edit the wind rose and it is possible that I created this one while fixing other bugs. I will fix it very soon.

**Comment by ayezioro** [comment]
Hi Chris,
Can be useful having the title with both printings.
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
I seem to have misunderstood this as a bug (it was more of a feature request) but I addressed it anyway.  You now get the percentage of hours in the analysis period:
![fixedwindrosetitle](https://cloud.githubusercontent.com/assets/5567574/6676601/97345f78-cbff-11e4-915d-5732f165363a.PNG)

Also, the title now comes as a separate output:
![fixedwindrosetitle2](https://cloud.githubusercontent.com/assets/5567574/6676598/93f5aa06-cbff-11e4-8846-bda2d90c326b.PNG)

-Chris

**Comment by ayezioro** [comment]
Great!!
Thanks,
-A.
