### ISSUE TITLE
Having issues with the new importEPW

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#136]
Hi Mostapha,
Just updated to the new version of components and the importEPW is making me trouble. As a matter of fact it is working but when i connect it's outputs with other dependant data component they are failing. For instance windRose (1. Please provide valid lists of hourly wind direction and hourly wind speed!) and sunPath with anniualHourlyData (1. Solution exception:invalid literal for float(): Tel Aviv-Bet Dagan_ISR).
Of course the KB_LB was also updated though its date is not of today's but 28.2.
Didn't check further with other components.
Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
This is my fault not testing it more in-depth. I'll check it out now and see if there is an easy fix for that. Sorry and thanks for reporting. I think we should use your files for testing new components.

**Comment by mostaphaRoudsari** [comment]
It should be fixed now! Thanks for reporting.

**Comment by stgeorges** [comment]
The error was mine.
Apologies to both of you, for this.

**Comment by ayezioro** [comment]
Thanks!! And no problem.
You know i like to test :-)
-A.
