### ISSUE TITLE
Wind Rose and Profile define desired hours

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#140]
Hi,
A wish:
i want to be able to define determined hours of the day for both Windrose and Wind Profile components.
I find rather useful to  be able to have this option if i want to check different scenarios, for example, day hours, or night hours (night ventilation), etc. Kind of what is possible with the Sunpath inputs.
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
You should be able to pull out specific hourly periods with the analysisPeriod.  The Wind profile component also includes a HOY input to pull out individual hours.
Let me know if I am understanding your request correctly.
-Chris

**Comment by ayezioro** [comment]
Hi Chris,
Let's say that i want all January JUST from 10 am to 18 pm. If i use the AnalysisPeriod it will start from 10 am for the 1st of January but in the 2nd it will start from 1 am (and so on, and so forth).
The idea is to be able to analyze ranges of hours of the day for a period of time.
The HOY gives one specific hour. Is not what i want.
Makes sense?
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
I think that you are misunderstanding how the function that reads the analysis period works (specifically, the function called lb_preparation.getHOYsBasedOnPeriod()).  It works just in the way that you are requesting here.  Perhaps hooking up the analysis period to the sunPath will make this clear.
This is the function that is used to read the analysis period across all Ladybug and Honeybee components.  The only case where the analysis period will not be read this way is when you plug it in for an E+ simulation, in which case, all hours between the start and end hour are run.
-Chris

**Comment by ayezioro** [comment]
Hi Chis,
... shame on me, a little bit.
So it does work as i want with the analysis period.
On my behalf i would say that a while ago, when Mostapha changed the Sunpath analysisPeriod i didn;t like that i usually want just one day to be mapped and with the analysis period you get the range of days (if you ask for more than one month). So i assumed that with the hours you get the same way of work when you ask for more than one day. That was my mistake. Sorry about that.
Thanks,
-A.
