### ISSUE TITLE
Change the license to GPLv3

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#147]
Read more on Honeybee issues (https://github.com/mostaphaRoudsari/Honeybee/issues/335) and please leave your comments under that post. Thanks.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
In light of the warnings that Pouya gave us the other day, I was curious about what is currently holding us back from updating the license.  If it is just a matter of writing a script to change the name of the license in the .py files, I would be happy to take care of it (or at least take a stab at it and hopefully figure it out).  I imagine that we also want to have an official announcement of the licence with the upcoming stable release in a month. Let me know what you are thinking when you get the chance.
-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey thanks. I had some progress after we talked and the draft version is ready to go. please check the email that I sent. As soon as we get the issue for CBE Tool fixed I can change the license for both Ladybug and Honeybee.

**Comment by mostaphaRoudsari** [comment]
Done via 5aa5c166ee81a92fce57ed52a84168d72deb56d4!
