### ISSUE TITLE
Identify annual cooling and heating period

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#15]
HDD and CDD calculator, radiation rose, and genCumulativeSky may have the option to read the weather file and separate the cooling period and the heating period.

It could be done using the old-fashioned degree days way (ESP-r cookbook is a good resource to look at), or it could be done by running an EP simulation so the schedule and internal loads will be considered in calculations.

ESP-r cookbook: http://www.esru.strath.ac.uk/Documents/ESP-r_cookbook_july_2011.pdf

**Comment by chriswmackey** [comment]
I don't know what is being referred to here that is different than what the HDD/CDD component already does but I trust @mostaphaRoudsari knows what it means and will take care of it.  Aslo, that link is broken @mostaphaRoudsari .

**Comment by mostaphaRoudsari** [comment]
Having all the comfort analysis functionality this will have no use anymore.
