### ISSUE TITLE
Don't use CC for your licensing!

### ISSUE THREAD

**Issue by pmkary** [mostaphaRoudsari/ladybug#153]
Hi! 

I was reading your codes that I found out you use CC for the license of both Honeybee and Ladybug. The thing is you [can't and must never](https://wiki.creativecommons.org/wiki/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F) use Creative Commons as the license for a software. CC supports anything but software. 

Using a wrong license is really dangers. I think it be awesome if you read [this](http://www.oreilly.com/openbook/osfreesoft/book/ch06.pdf) and then check out Apache License, MIT License and GNU GPLv3 and take a fast action to change your licensing before it's too late.

Wishing you all the best with all the projects

**Comment by mostaphaRoudsari** [comment]
Hi @pmkary! Thank you for opening this issue. You're right and as you can see here we're in the process of changing the license: https://github.com/mostaphaRoudsari/Honeybee/issues/335

Duplicated with https://github.com/mostaphaRoudsari/ladybug/issues/147

**Comment by pmkary** [comment]
Thank for the reply.

I'm glad you know the issue, but a bit amazed it's taking you time to changed it. I think you should hurry a bit when it's about these legal stuff, I've been in GNU for a few months and there are really horrible things going on about all the companies that use these pitfalls to take advantage of open source software and it's just sad. I really think you better change the license as soon as possible.

Regards
Pouya

**Comment by mostaphaRoudsari** [comment]
@pmkary now Ladybug is under GPL!  :tada: :balloon:  (5aa5c166ee81a92fce57ed52a84168d72deb56d4)

**Comment by pmkary** [comment]
That is excellent! congrats on that :D
