### ISSUE TITLE
Bug - Bioclimatic Chart

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/ladybug#154]
Hi @ayezioro 
There is still a bug in the Bioclimatic Chart with the coloring of points that is in the comfort range or not. The color should just be swapped.
![ladybug_biochart-03](https://cloud.githubusercontent.com/assets/7299731/8754116/7b15802e-2cc1-11e5-8878-bbdec4fca3ec.JPG)

**Comment by ayezioro** [comment]
Hi Daniel,
Sorry for the delay.
Please find attached the update:
https://www.dropbox.com/s/y0glp1eqs5zk1lq/ForGithub.zip?dl=0
There is also the updated example.

Mostapha and/or Chris: Do you mind tu upload this stuff to the github and examples location?
For you is a minute for me can be ... many "minutes" :-)

If it is ok you can close the issue.

Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
Hi @ayezioro, Thanks! It's pretty easy for me to do but I would say let's take the time and commit it from your account. I want your work to be committed as yours. I'll be around tomorrow. Let me know if you want me to help you online through skype so we can do it together in matter of minutes. You just need to sync your fork with the master, make the changes and send a pull request! Let me know if your choice!

**Comment by ayezioro** [comment]
Hi Mostapha,
Great!! Just for having the opportunity to chat with you i'm willing to do this.
Our time difference is 7 hours. Let me know when it is fine for you.
Thanks,
-A.

**Comment by arkdanielnielsen** [comment]
I would also like to see how it is done. I have still not uploaded the simple component that convert from kW to W. 
@mostaphaRoudsari maybe you could setup a small session on how to do that :)

**Comment by mostaphaRoudsari** [comment]
Sounds good! Just sent an email.
