### ISSUE TITLE
Ladybug_Ladybug component not in LB group

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#159]
Hi,
I updated with the last version on the github. Now i notice that the LB_LB component is not anymore in the under the Ladybug tab group. It shows now in a tab called User.
Weird, ah?
-A.
![capture](https://cloud.githubusercontent.com/assets/7526023/8990890/d1ed212c-36fd-11e5-8bce-9f528d276f3f.PNG)

**Comment by mostaphaRoudsari** [comment]
Hi Abraham. Thanks. Very strange! Can you try now? I recompiled the ghuser. It is now fine on my system.

**Comment by ayezioro** [comment]
The bug is not alone anymore :-)
Thanks.
-A.
