### ISSUE TITLE
montly total cannot be visualized by 3D chart

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#160]
See this: http://www.grasshopper3d.com/group/ladybug/forum/topics/montly-total-cannot-be-visualized-by-3d-chart?page=1&commentId=2985220%3AComment%3A1333170&x=1#2985220Comment1333170

**Comment by chriswmackey** [comment]
Fixed:
https://github.com/mostaphaRoudsari/ladybug/commit/633bcd3105a9647dd6eec12b328c9a8daac74d83
