### ISSUE TITLE
Shadow mask top sky patch should be splitted in smaller pieces.

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#165]
See this discussion: http://www.grasshopper3d.com/xn/detail/2985220:Comment:1339963

**Comment by devngc** [comment]
@mostaphaRoudsari,
Did we not address this in #319?
-Devang

**Comment by mostaphaRoudsari** [comment]
@devngc this is the other mask component which has a segmented sky.

**Comment by chriswmackey** [comment]
This has been addressed via https://github.com/mostaphaRoudsari/ladybug/commit/bd217eb061750b9fd8a9e817a400aefbb02123f1
