### ISSUE TITLE
Radiation Analysis Generates Points Below Surface for Doubly-Curved Geometry

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/ladybug#167]
This issue spun out of another one here:
https://github.com/mostaphaRoudsari/ladybug/issues/161#issuecomment-127084364

The problem is that, for complex curved geometry, test points can be accidentally generated below the test surface.  I do not yet know the best way to fix the code but I do know why it is happening and I have two temporary workarounds.

The two workarounds are either:

1) Triangulate all of the faces of the brep before connecting it to radiation analysis, which ensures that all generated faces are planar (thus avoiding double-curvature):
triangulated mesh

2) Increase the distFromBaseSrf to a value that ensures that all generated points are far enough away from the base srf that they are not accidentally located underneath it:
increase distfrombasesrf

Since the radiation component is @mostaphaRoudsari 's, I feel that the decision is up to him whether he wants to address this type of case in the code and how it should be done. It seems that @ayezioro prefers to automatically triangulate the doubly-curved quads and I think that I would prefer the same (although I think that this is admittedly harder to implement than simply giving the user a warning to increase the distFromBaseSrf).  @mostaphaRoudsari , I am happy to help implement one of these options if you have a preference.  I am worried that the triangulation I was trying before would increase the run time significantly and so I would recommend you take a look at this example file before making a decision:
https://www.dropbox.com/s/hl8bt9abzo0a9pa/solarEnvelopeAdvanced_ToReport_boris_5.8_5_AY_CWM.gh?dl=0

-Chris

**Comment by ayezioro** [comment]
Hi Chris,
After checking some cases (see discussion #161) i've found that the triangulation solution is having some inconsistencies in the quality of the calculated envelope. As a result i'll recommend by now, just to warn the user that in cases the points fall below the surface, to increase the distance to surface input.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Awesome.  This will be much easier to implement.  I should be able to take care of it soon.
-Chris

**Comment by chriswmackey** [comment]
I realized that this would add a significant amount of time to the calculation to check if a point is below the surface and I think the best we can do is just keep requiring the user to input a _disFromBase, which is the correct way to address this issue.
