### ISSUE TITLE
SolarFanBasic / SolarEnvelopeBasic updates

### ISSUE THREAD

**Issue by saeranv** [mostaphaRoudsari/ladybug#173]
@mostaphaRoudsari , @chriswmackey , @ayezioro 

Hello all, it took a while but I have updated my components in response to @ayezioro 's suggestions and some other overdue changes. Example file can be downloaded here: https://drive.google.com/file/d/0B1aL4rZ85UMSVHBxUE5jcDBsRjA/view .    

Changes are:
* clarified requiredHours input with example
* rewrote the description to distinguish these components from the other solar components (i.e as Basic component that can construct envelope/fans with minimal inputs. Predefines monthly ranges / hourly ranges.)
* fixed missing input data types
* changed title to SolarFanBasic / SolarEnvelopeBasic to differentiate from new component 
* changes to geometry: add more solar vectors to solar envelope for increased accuracy

Let me know if these are good, or if you'd like any further changes...

**Comment by ayezioro** [comment]
Hi Saeran,
Looks fine for me.
Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
Hi @saeranv! Thanks. It all looks good to me too. The only minor comment is that you should leave the type for north input as NoTypeHint if you want users to use either a number or a vector to change the north. Currently only vector will work because of the type hint.

**Comment by chriswmackey** [comment]
Glad to see this and looking forward to integrating it once a new pull request comes through with the right north vector type hint.

**Comment by saeranv** [comment]
@mostaphaRoudsari , @chriswmackey 

Thanks guys, I updated the type hint as suggested and sent the new pull request.

**Comment by mostaphaRoudsari** [comment]
Merged! Thanks @saeranv
