### ISSUE TITLE
Let multiple versions of ladybug+honeybee fly next to each other

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#175]

**Comment by mostaphaRoudsari** [comment]
@chriswmackey I gave this a second thought and it's doable but needs changes to the way we keep Ladybug and Honeybee libraries in sticky. Here is how I can think about implementing the process which needs to update all the components! We can automate the process but even automating the process will take some time.
[**1**] First change is that ```versionCheck``` class should keep track of all different versions flying around. This is pretty straight forward to implement but then [**2**] all the libraries should be moved to ```sc.sticky[ladybugVersion]['name of module']``` this is also easy as can be implemented to Ladybug_ladybug and Honeybee_Honeybee. It's not going help with older versions of ladybug and honeybee since they don't follow this structure but that's fine if we consider that it will be helpful from now on. Oh wait... this will break older versions since they are looking for version using ```versionCheck``` and now it will return a list. That means we need to move the versions under a new key. That's fine too.

Up to this step, it's easy to implement but then now all the other components need to load the libraries from the right version. It means ```lb_preparation = sc.sticky["ladybug_Preparation"]()``` won't work anymore. and you need ```lb_preparation = sc.sticky['THEVERSION']["ladybug_Preparation"]()``` but the versions are changing on daily basis and the version that the component is looking for may or may not be available. Let's talk about 3DChart. It's currently looks for ```#compatibleLBVersion = VER 0.0.59\nFEB_01_2015``` but the current version is ```VER 0.0.60\nSEP_21_2015```. The component first starts to look for it's own version and if it can't find the version it looks if there is a newer version available and if it finds a new version it will load that otherwise it will complain that the component needs a newer version of ladybug to fly--- This is also doable but then here is the case:

Imagine a user takes legendParameters from and old version (which now will work because we implemented the new workflow), and connects it to a newer component (which is also working since we made it to work) and boom the component will crash and we helped it to happen! Now the question is does it worth implementation assuming the cases like this that can happen. I rather to spend this time and improve update components and then ask users to keep syncing their definitions with the latest version. Thoughts? 

@ayezioro and everyone else please feel free to share your thoughts about this.

**Comment by ayezioro** [comment]
Hi Mostapha and all,
On this kind of issues i'm pretty clear cut. Go only for the last/updated version. The amount of trouble that can arise from multiple versions (as the example Mostapha mentioned, but God knows how many other situations you can have) against the trouble you have now with those that don't update, in my opinion, will be much massive and disappointing.
The update process today is not that complicated, hard to do, etc. Thinking on this, maybe a new component, "CheckYourVersion" )or something like this), can report if you are running the last version and even tell you what components need to be reinserted, or are no longer existing. Something to think about ...
Make any sense ...?
-A.

**Comment by ayezioro** [comment]
One more thing related to discussions and advise.
I'm afraid about the relevance and quality of the discussions based on "old" components. The level of "concentration" you need to give advise is a major task. I think about myself, for instance, if not you (Mostapha and Chris). Probably you'll be the only ones able to manage this ping-pong between versions.
I'm seeing this much more darker than what it could be? Maybe ... but i think that not always you need to allow all the possibilities because it is possible, but rather enable what is needed.
-A.

**Comment by mostaphaRoudsari** [comment]
Hi Abraham. I can't agree more with your comments, and the concept of ```CheckYourVersion``` is already implemented for Honeybee_Honeybee and Ladybug_Ladybug. It is possible to implement it to all the other components too as ```isNewerVersionAvalilable```. I will keep this open to get @chriswmackey's comments and will be working on the other issues to get the new release out on-time!

**Comment by ayezioro** [comment]
When is the release scheduled? I have one component (lookupE+Folder) that i was working on and didn't finished. Almost there ...

**Comment by mostaphaRoudsari** [comment]
We should have all the components updated by Tuesday evening Serbia time! Hopefully not later than Wednesday morning EST.

**Comment by ayezioro** [comment]
Arghhhhhhhhh ....!!!!

**Comment by mostaphaRoudsari** [comment]
@ayezioro does it mean that you need more time?

**Comment by ayezioro** [comment]
Oh yes.
But go ahead with the schedule. I don't want to hold this release. I'll update the github later on.

**Comment by chriswmackey** [comment]
@ mostaphaRoudsari and @ayezioro ,

It seems that this has ended up being a much more complicated issue than the simple statement that you had given me in conversation, Mostapha.

I certainly understand the case that you have presented and I agree with what we have decided regarding this issue given only one condition - we aim to have stable releases on a slightly more regular basis. This is the ultimate reason why I had asked about how to deal with this inter-version capability and it would not be an issue if we were releasing every 3 months or so.

Needless to say, I think that the time period of this last release was way too long and I feel that we should be releasing this upcoming week with a plan to do another release at the end of January.  Hopefully, this will give you a new deadline, Abraham, if this current one seems difficult to hit.  This said from previous experience, we are aiming for Tuesday but you may have a grace period of a day or two.

Let me know if this plan sounds good and, if so, let's close out this issue.

-Chris

**Comment by ayezioro** [comment]
Good. I'll pick the january release, hoping i'll send something before that for testing.
Right now this semester is overladed for me to be able to catch this coming date.
-A.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey I agree that when we had the discussion I personally didn't think of all the issues that this can bring. I totally agree that we need to have more frequent releases for the stable version and I take responsibility of the major delay for this release. I will close this issue and open a new one for ```checkGrasshopperDefinition``` which will comment the definition based on new version availability. As a part of that I will add a check for inputs and outputs so once the components get updated the user will be notified about the components that needs to be replaced by a new one because of changes in number of inputs and outputs.
