### ISSUE TITLE
Add Decimal Places as Input to Legend Parameters

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/ladybug#183]
I have realized that this would be really useful for the quick creation of nice graphics.

**Comment by mostaphaRoudsari** [comment]
:+1: Very very useful and pretty straight forward to implement. Thanks for adding this

**Comment by chriswmackey** [comment]
This had been added a month ago and I forgot to close out the issue.  It has made things sooo much easier in my graphics workflows.
