### ISSUE TITLE
Extra output lines on LookupFolder_Daylighting 

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#184]
The analysisType output of the LookupFolder_Daylighting component is giving an extra line with a "%" in it, while the same output from the runDaylightAnalysis is giving only one line. This extra output gives an error when trying to plot results frfom existing files.
See this discussion for details: http://www.grasshopper3d.com/group/ladybug/forum/topics/daylight-analysis-index-out-of-range-frozen-stuck-cmd
-A.

**Comment by ayezioro** [comment]
Oooops, 
This issue should be in the HB section. Sorry.
-A.

**Comment by mostaphaRoudsari** [comment]
![separateoutputs](https://cloud.githubusercontent.com/assets/2915573/10543283/81763898-73eb-11e5-9ee4-b98146b42b2d.png)
