### ISSUE TITLE
Create a component to check Grasshopper document for potential components to update

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#192]
This can be like a git comparison code that checks the document. Finds all the components for ladybug and honeybee, finds if there is a newer version and finally does a check to see if there will be a conflict and will report this to the user.

PS: This will be very cool!

**Comment by mostaphaRoudsari** [comment]
Thanks @ayezioro  for the suggestion!

**Comment by chriswmackey** [comment]
This was implemented in the last release.  And a wonderful component it is!
