### ISSUE TITLE
IMPORTANT: Hydra Example Files for the Updated Release

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/ladybug#198]
Hello All,

In order to prepare for the next stable release, we are asking that everyone who has contributed example files to our original app.box location create hydra examples of their GH files to make it easier for everyone to search and explore each other's examples (and also so that each of you have the ability to update your own examples in the future whenever you make an improvement or change).  For those of you who are unfamiliar with Hydra, it was born out of a hackathon that @mostaphaRoudsari and I attended and is a github-based platform for sharing grasshopper example files (https://hydrashare.github.io/hydra/index.html).
If you are able to put up your examples within the next 24 hours, we can ensure that your example files are cited in the release notes of the next stable release.  Otherwise, we can add them in later.  If you could post here once you have made your hydra examples, that would help us make sure that we put your files into this release.

You can find instructions for how to create hydra examples here:
https://github.com/HydraShare/hydra/wiki
And a video tutorial here:
https://www.youtube.com/watch?v=bt34UvzLwgY

As of now, I have the following examples in our app.box assigned to the following developers:
15_Bioclimate Chart (Abraham) (@ayezioro )
20_Solar Envelope Advanced (Boris) (@boris-p )
020_HB_Earth Tube (Anton) (@antonszilasi )
017_HBGeneration (Anton) (@antonszilasi )
Extra Files by Daniel Nielsen (Daniel) (@arkdanielnielsen )
Photovoltaics Components (Djordje) (@stgeorges )

Thank you all in advance!
-Chris

**Comment by boris-p** [comment]
Cool stuff !
Hope i'm not too late, updated and uploaded the solar envelope example - http://hydrashare.github.io/hydra/viewer?owner=boris-p&fork=hydra&id=20_LadyBug_solarEnvelope

hope it's on par with the other examples as far as the standards go, maybe you could just glance at it to make sure

boris

**Comment by ayezioro** [comment]
Hi,
After seeing Boris's comment i see that mine from this morning is missing :-(
I synced (or at least i think i did) 4 examples (3 of them i uploaded a while ago):
02_Radiation_Vectors2SkyPatches_01
Bounce_Out
view_TowardOrFrom_Sun_01
and the new
Bioclimatic_chart_example

Hope all of them will get there safely.

Thanks,
-A.

**Comment by ayezioro** [comment]
Hi again,
I see that 3 of the examples were updated. The new one is still not up (Bioclimatic chart). Anything i can do?
-A.

**Comment by mostaphaRoudsari** [comment]
Hi Abraham and Boris. It's all there now. It takes couple of minutes for the main page to load new examples. You're all good! Thank you for doing this.

**Comment by mostaphaRoudsari** [comment]
two minor comments here:
1. I think we don't need the numbers in front of the examples. We will make a numbered list and link to Hydra examples.
2. Should we all consider the same tag for official examples? I thought of LBExampleFiles for Ladybug and HBExampleFiles for Honeybee. This way we can have all the official examples being filtered using these two tags.
You can make this changes whenever you have time. Thanks.

**Comment by ayezioro** [comment]
Hi Mostapha,
I think is good idea to have a key for the examples.
Question: If i change the name of the file it will change/erase the previous one? Or how can we avoid having both of them?
-A.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

You just read my mind and I was just about to post regarding these things.  The tags LBExampleFiles for Ladybug and HBExampleFiles are good.  @ayezioro and @boris-p .  Thank you for putting your files up.  If there is one last thing I could as you to do it is put these tags in your hydra pages and take the numbers out of the title.

I apologize for not specifying these things sooner.
-Chris

**Comment by chriswmackey** [comment]
@ayezioro ,
You should delete your old file's folder in your github folder before making a new hydra to ensure that you do not make a duplicate.
-Chris

**Comment by stgeorges** [comment]
I am not let to choose the @username once I try to for Hydra, as shown in [Chris tutorial video](https://www.youtube.com/watch?v=bt34UvzLwgY).
It simply just forked like any other regular repository. Am I added to the list or users?

After forking, I only get:

LICENSE and README.md

files in the forked repository.

Is all of this correct?

**Comment by mostaphaRoudsari** [comment]
@stgeorges yes. That is correct. You're good!

**Comment by ayezioro** [comment]
Hi Chris,
Now i understand the tag request. But let's say i want to change the name of an example (from 02_XXX to LB_XXX). The previous version in Hydra will remain or it is smart enough to understand the change?
-A.

**Comment by mostaphaRoudsari** [comment]
Hi Abraham. I think I can help with that one. If you rename the **folder name** in your github folder, github will consider that the old folder is removed. This will be also the case for Hydra. Hydra refreshes the link every 15 minutes from github forks and whatever change you make in your local fork will effect the main page. Think of it as a *distributed* file sharing system.

**Comment by chriswmackey** [comment]
@ayezioro ,
Unfortunately, the name is the identifier of the hydra so, once the name is changed, the original hydra pages and all of the links to it are gone.  That is one reason why we would like you to identify your files with a solid title that will not change (even if numbers eventually change).
-Chris

**Comment by arkdanielnielsen** [comment]
Hi guys
I am wondering if those extra example files I have created have any value, because in a way they are shown in other example files more less.
/daniel

**Comment by boris-p** [comment]
Updated file (new name + tag) - http://hydrashare.github.io/hydra/viewer?owner=boris-p&fork=hydra&id=SolarEnvelope

**Comment by mostaphaRoudsari** [comment]
Thanks @boris-p it looks great. As a side note you can still have multiple tags so people can find your example with related keywords. If you just have LBExampleFiles as one of them it will work for our purpose.

Hi @arkdanielnielsen, There is definitely no pressure to update all the example files. If you think there is any of the examples that worth being part of the package then just update that file. We will release around midnight EST time.

Thank you all.

**Comment by ayezioro** [comment]
OK.
Committed and synced. Changed the names (where needed) to something more consistent, and tagged as requested.
Hope it is fine.
-A.

**Comment by chriswmackey** [comment]
Everyone,

Given that we are long past the release, I am going to close out this issue.  I think that everyone has updated their example files with the exception of @antonszilasi 's earth tube and generator examples, which I know he has said that he would post soon.

-Chris
