### ISSUE TITLE
Psychrometric Chart Crashes when Connects windSpeed

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#209]
@chriswmackey can you take a look at [this discussion](http://www.grasshopper3d.com/group/ladybug/forum/topics/psychrometric-chart-crashes-when-connects-windspeed). I believe that this was an issue with older SRs of Rhino.

**Comment by chriswmackey** [comment]
This issue has been closed for a while.  It was just that you really are not meant to connect up 8760 values to the wind speed.
