### ISSUE TITLE
Microclimate Map Analysis error with latest version

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/ladybug#213]
Hello there,

I synced my definition with Github and this component returns the error:
"Solution exception:Local variable 'FinalHOYs' referenced before assignment."
Previous version from November 11 works fine.

![image](https://cloud.githubusercontent.com/assets/8501837/11895945/d332398e-a582-11e5-88b5-d4fb7b3ed422.png)

**Comment by chriswmackey** [comment]
@jacoposartore ,
This sounds like it is the result of some recent changes I made to be able to run analysis periods where the start date occurred later in the year than the end date. Can you post a link to the GH file with the error?
-Chris

**Comment by jacoposartore** [comment]
@chriswmackey,
my file was too complex to be uploaded, therfore I created a new one from scratch that generates the same error.
Here it is https://www.dropbox.com/s/fhqhw38tasithkk/MicroclimateMapError.gh?dl=0.

**Comment by chriswmackey** [comment]
@jacoposartore ,
Thanks for the file.  The error was a small one and it is fixed:
https://github.com/mostaphaRoudsari/Honeybee/commit/7b8bb1922e666a9664e24c91a3f35d506b30b2c3

Thank you, again, for reporting this. 
-Chris
