### ISSUE TITLE
missing Bold input - Ladybug_Legend Parameters

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/ladybug#214]
I am missing the possibility to make the text bold. When exporting graphs as images I think it makes the text more visible to have it Bold. Is there a reason for why it is removed?
![ladybug_nobold-01](https://cloud.githubusercontent.com/assets/7299731/11905392/97161b66-a5c6-11e5-9162-5df86778fec7.JPG)

**Comment by chriswmackey** [comment]
@arkdanielnielsen ,
In the interest of making the component more compact, the bold input has been integrated into the font input in the current version.  Read the font input description to see how to request bolded fonts:

font_: An optional text string that sets the font of the text. Examples include "Arial", "Times New Roman" or "Courier" (all without quotations).  The text input here can be any font that is on your computer but the font must be of an Editable file type (as seen in the font folder off of your control panel).  Font files that are Print and Preview will not work.  If you wish to use a Bolded version of the font, include a ", Bold" at the end of the font name (example: "Arial, Bold").

-Chris
