### ISSUE TITLE
problem with radiation diagram

### ISSUE THREAD

**Issue by jpcostaa** [mostaphaRoudsari/ladybug#221]
Hello Mostapha,

Firstly, amazing work with LB and HB. You are doing a lot for community that needed this.

I've got a problems in my hands, its not something new as I have been searching online, and there are no solutions yet. It can be found here:
http://www.grasshopper3d.com/forum/topics/weird-radiation-result?groupUrl=ladybug&groupId=2985220%3AGroup%3A658987&id=2985220%3ATopic%3A1425721&page=1#comments

Anyhow, I have been trying to analyze the radiation on an specific surface (it could be Brep too). 
the resulting graph of my radiation analysis is only a huge blue tone on my subject of analysis.. everything shows up as 0 kWh/m2. I could work with the same files (.gh , .epw , and even .3dm) in other computers and its works perfectly fine, lots of detailed results come up.
I can use Ladybug for other analysis (drybulb temperature analysis mostly) in my computer and its working well.. so I believe it isn't a LB problem. 
I am using a mac with windows 7 through parallels and haven't have any troubles.

Do you know how this could be fixed. I am getting a bit desperate.. at least point in my a direction.

Thanks so much!

JP

**Comment by mostaphaRoudsari** [comment]
Hi @jpcostaa, Thanks. I replied in the group. The issue is probably that Windows has blocked gendaymtx.exe file. Check the link that I provided in the group and that should solve your problem. I added an extra check for the next release so it will give you a warning.
