### ISSUE TITLE
New baking options

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#228]
Hi Chris,
I've been checking the new baking options (1- hatch, 2- Mesh).
For some reason it doesn't matter if i choose 1 or 2 the baked geometry are always hatches.
Checked the code and i see the True/False parameter. Everything is looking right but the result is not.

I'm missing something (probably) or this is an issue?
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Which component is this? I manually checked all of the components after I made the change and all of them had this ability as of the update I finished 8 hours ago. Could it be possible that you were not using this most recent version?  Also, if you did not update your component by placing it manually on the canvas, the BakeIt input will not be canged to an intended type.
-Chris

**Comment by ayezioro** [comment]
You are the man!! This is it. I didn't reinserted them because they didn't complain.
This is posing a new level of update now: You do the update as usual (update component), but those new components won't complain but also won't fully perform unless ... you reinsert them. Hmmm.
So, for now, you'd say that all components that have a bakeIt option should be reinserted for fully performance?

Thanks and sorry for the false alarm.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Yes, the not complaining of the components happens when I only change the type hint but not the name of the input.  I was debating whether to make the change more drastic so that the component would fail but decided that it might be nicer to have the updated components still functional without reinsertion since the full capabilities of bakeIt are not a critical feature and not everyone will want to update all of their LB their components for this subtle change.
To get full access to the new bakeIt feature, you can either reinsert the component or change the bakeIt type hint from 'bool' to 'int'.
Glad that you like the new feature!
-Chris

**Comment by ayezioro** [comment]
Txs.
-A.

**Comment by ayezioro** [comment]
Hi Chris,
I'm using the baking option with the windRose component. I'm getting the following error:
> 1. Solution exception:expected Mesh, got int
Testing the code i see:

> Invalid Mesh!
> Runtime error (ArgumentTypeException): expected Mesh, got int
> Traceback:
>   line 597, in main, "<string>"
>   line 632, in scrip

I assume that this is maybe caused by some tolerance problem with small sizes. But changing the tolerance doesn't solve the issue.
Any ideas?

Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
It's probably for an hour with no value that windrose returns -1

**Comment by chriswmackey** [comment]
@ayezioro ,
I can't re-create your error on my machine.  Hours with no values give the usual 'no hour meets the conditional statement' message.  Please upload a file with the error.

-Chris

**Comment by ayezioro** [comment]
The GH file is:
https://www.dropbox.com/s/qbppbggerzzuxod/04_WindAnalysis_01_HaifaBatGalim.gh?dl=0
and the epw:
https://www.dropbox.com/s/p85qg64wag2gmm4/HaifaBatGalim-SPtMasterTable_552848_19790101_20110101_TMY3.epw?dl=0
This is a synthetic file.

See the components at the bottom where i analyze specific months.
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
@mostaphaRoudsari was right.  I just did not understand.  It has been fixed:
https://github.com/mostaphaRoudsari/ladybug/commit/db82d42036ee9412ea4a605fe5be10c8476aef42
-Chris

**Comment by ayezioro** [comment]
Thank you!!!
-A.
