### ISSUE TITLE
Consider Removing 'Vertical Sky Component' and Instead Have People Run Daylight Factor with 1 Ambient Bounce

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/ladybug#230]
as per this conversation:
http://www.grasshopper3d.com/forum/topics/sky-view-factor-vs-vertical-sky-component?groupUrl=ladybug&xg_source=msg_com_gr_forum&groupId=2985220%3AGroup%3A658987&id=2985220%3ATopic%3A1377260&page=1#comments

**Comment by ayezioro** [comment]
Hi Chris,
It is i,mportant to leave all components:
Sky View: Besides what you mentioned in the discussion they gave a visual assessment (for a point in space), which i think is VERY valuable (for work, for teaching, etc). Now with your visualStudy you get this  for the whole space, which is much greater.
VerticalSky: Agree that is not much used, and even a bit outdated. Saying that there are places that use it an even request to deal with it. This link, http://www.waterslade.org/main.htm (which is sometimes up and sometimes down) shows this nicely, when through this measure you check the potential of daylight (is checked on the facade).
The only "risk" is that users can use one of them meaning the other (specially VSC for SVF). But maybe a good explanation/warning can be provided so beyond the use, users can be educated a little bit. Besides that they/we are responsible of understanding what we are doing.
I'm in favor of leaving the VSC. The pros are bigger than the cons ... for me.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

I understand your concerns and I definitely agree that we should not be removing any capabilities for people who know what they are doing.  Because of this, I realized that my original title for this issue was not well-chosen and what I meant to discuss here is just a matter of what the workflow should be for running VSC simulations.
Essentially, all that the VSC component is doing is setting up a Daylight Factor simulation with 1 ambient bounce, which is something that users can already do with the Daylight Factor analysis recipe.  My thought is that, if users set up a VSC simulation with the DF component, they will be much more aware of what they are running and won't fall as easily into the trap that we did in thinking that VSC was the same as skyview.  The other way of addressing the issue is just to leave the VSC component but try to make it very clear in the description what VSC is, what it is used for, and emphasize that it is not the same thing as skyview factor.

In light of this redefinition of the issue, let me know if you are still on the side of leaving the VSC component and beefing up the description.  I think that I might still be on the side of having users run the DF component but I was not able to access the link that you posted (I'll try again later) and perhaps a better understanding of how/why people are using/requiring VSC would convince me that this 'shortcut' component is useful.

-Chris

**Comment by ayezioro** [comment]
Hi Chris,
I'm for leaving and explaining better.
In any case the VSC is not exactly DF as you can see here:
https://consultations.rics.org/consult.ti/daylightingsunlighting/viewCompoundDoc?docid=2858900&partId=2859860&sessionid=&voteid=:
"the Vertical Sky Component [VSC] assessment - the percentage of the total sky that can provide direct light to the centre of the face of the window when neighbouring obstructions are taken into account"
Which means that one looks for the % of sky and the other the % of external light amount.
The link inn the previous comment seems to be really broken but i've just see it a few days ago. It is much clearer.
Some more explanations here:
https://www.lightup-analytics.com/home/features/vsc/
-A.

**Comment by ayezioro** [comment]
I don't know how/why the following went to another issue. Was supposed to be here. Here it is:

As for the broken link, this is weird, but if you google waterslade (https://www.google.co.il/search?q=waterslade&ie=utf-8&oe=utf-8&gws_rd=cr&ei=GDOuVum3BIb9sQHdzae4BA) you'll get the main page. Look there for the "dev_potential" image (the one with the red buildings).
So weird.
-A.

**Comment by mostaphaRoudsari** [comment]
I see @chriswmackey's point but then we can say daylight factor is also a grid-based analysis with overcast sky where the user should divide the results by sky illuminance to get the percentage? I also think having a separate component is helpful specially for teaching purpose.

**Comment by ayezioro** [comment]
The correct address for the link i mentioned is now: http://www.waterslade.com/main.htm
Just if interested in seeing some definitions on VSC.
-A.

**Comment by chriswmackey** [comment]
@ayezioro  and @mostaphaRoudsari ,
It is very clear to me now how the VSC component is useful after reading your links, Abraham, and understanding the distinction that Grasshope points out on the GH forum:
http://www.grasshopper3d.com/group/ladybug/forum/topics/discussion-sky-view-factor

My only issue now is that we should probably be more technically correct and change the name of the component to simply be “Sky Component” instead of “Vertical Sky Component”.  This is because the Vertical Sky Component recipe for Honeybee might not always be evaluating VERTICAL sky.  The sky component might be vertical, horizontal, or in any direction that the input test surface is placed and ptsVectors are oriented.  This change in name might also be accompanied by a more thorough component description.

Please let me know your thoughts on these changes and if you feel otherwise.  And thank you so much for helping to clarify the purpose and differences of these metrics that we have been struggling with.  It has all been very useful to me and I hope that you feel that you have gotten some clarification out of it too.

-Chris

**Comment by ayezioro** [comment]
Hi Chris,
All this discussions are great. Of course all of us learned from them.
I related to your question above in the GH forum. Pasting the answer:
Agree that the VSC can be applied to any surface, and as a result of that the name change can be in order. But, just thinking/wondering, who will use this for any surface but vertical. This measurement is not giving any useful information for them. At least not what it was intended for. This as opposed to the SVF.

So instead of changing the name, and diluting the original purpose of the component, maybe a warning or an explanation showing the purpose of the analysis will be better.

This is one of those situations that "just because it is possible to do" can be lead to conceptual mistakes.

What do you think?
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
I agree and let me know your thoughts on the comments that I have made on the GH firum:
http://www.grasshopper3d.com/group/ladybug/forum/topics/discussion-sky-view-factor?commentId=2985220%3AComment%3A1463328&xg_source=msg_com_gr_forum

-Chris

**Comment by chriswmackey** [comment]
@ayezioro ,
If you agree with all of the changes that I made, feel free to close out this issue.
-Chris

**Comment by ayezioro** [comment]
Yes. This was a a very good one!!!
Thanks a lot.
-A.

**Comment by chriswmackey** [comment]
Awesome.  I learned a lot in this discussion.
Issue closed :)
