### ISSUE TITLE
Double check north implementation for radiation rose

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#231]
Check this discussion: http://www.grasshopper3d.com/group/ladybug/forum/topics/radiation-intensity-values-for-radiation-rose-and-sky-dome-don-t

**Comment by chriswmackey** [comment]
The implementation is correct:
![image](https://user-images.githubusercontent.com/5567574/34280121-68533b9c-e683-11e7-9a68-543f48b2f976.png)
