### ISSUE TITLE
selectSkyMtx component uses one hour too many

### ISSUE THREAD

**Issue by jarno55** [mostaphaRoudsari/ladybug#233]
Hello ladybug developers. 

First of all i'd like to thank you for the great tool, it's very useful!

I wanted to tell you that i found a bug. The selectSkyMtx component does not assign the hours of a certain analysis period correctly. For example if i would like to analyse all hours from 11:00 to 12:00 over the whole year, the selectSkyMtx component actually chooses all hours from 10:00 to 11:00 as well as all hours from 11:00 to 12:00, leading to radiation results that are approximately twice as large as they should be. 

I did find a simple fix to my problem, by changing line 88 in said component to:

`if stHour <= (i + stHour - 1)%24 <= endHour-1: selHourlyData.append(item)`

(i.e. deleting the "-1" before the first smaller or equal sign).

I am however new to python and think maybe someone with more experience should have a look at it. I also believe that the analysisPeriod component should be set more clearly, right now with that component it is impossible to select the hour 0:00 to 1:00 (or 12 am to 1 am in US time conventions). I believe the input _fromHour_ should accept values between 0 and 23, whereas the _toHour_ can stay as is (1 to 24). 

Best wishes and thanks, Jeremy

**Comment by chriswmackey** [comment]
@jarno55 ,
Sorry for the incredibly late reply on this one.  This should be addressed now that we have the HOY_ input on the Select Sky Matrix component.  So you should just use the HOY_ input with the "Ladybug_DOY HOY" component to make a sky for just the hours that you want.  Unfortunately, for reasons that have to do with other analysisPeriod workflows, we cannot make this reference a single hour of the day. Thanks for bringing this to our attention, though.
