### ISSUE TITLE
Runtime error Ground temperature Visualisedata_Month

### ISSUE THREAD

**Issue by Omidmr** [mostaphaRoudsari/ladybug#237]
Hi everyone,

 I used "import Ground temperature" component for Visualisedata_Month returns this error :

data contains monthly average temperatures at 1 different depths 1.0 meters
Runtime error (ValueErrorException): too many values to unpack
Traceback:
  line 333, in drawprofileCrvs_Month, "<string>"
  line 462, in script

![ssds](https://cloud.githubusercontent.com/assets/11173265/13237482/b5743abc-d9e1-11e5-8215-cf1b9666d7e4.JPG)

Thanks,
-Omid

**Comment by antonszilasi** [comment]
@Omidmr  could you email me the file or better yet post the issue on the Grasshopper forms and link me to them

**Comment by Omidmr** [comment]
@antonszilasi 
I was sent to your email , please check that. 
thanks,
-Omid

**Comment by antonszilasi** [comment]
@mostaphaRoudsari At some point was the readLegendParameters function changed? 

With the line below I am getting the error, too many variables to unpack.

lowB, highB, numSeg, customColors, legendBasePoint, legendScale, legendFont, legendFontSize, legendBold = lb_preparation.readLegendParameters([], False)

This function is returning 11 variables when the code I initially wrote only "catches" 9. If I add two dummy variables everything works fine.

**Comment by mostaphaRoudsari** [comment]
@antonszilasi, Yes. @chriswmackey has added two new outputs.

[Here](https://github.com/mostaphaRoudsari/ladybug/blob/e0e0bfb3e80f6fd0bfdaa91129c807dd7b61623d/src/Ladybug_SunPath.py#L491) is an example which I found by searching searching [lb_preparation.readLegendParameters](https://github.com/mostaphaRoudsari/ladybug/search?utf8=%E2%9C%93&q=lb_preparation.readLegendParameters).

**Comment by antonszilasi** [comment]
@mostaphaRoudsari  Should be fixed now it made sense just to add two dummy variables.
