### ISSUE TITLE
bug: LB SolarFanBasic and LB SolarEnvelopeBasic

### ISSUE THREAD

**Issue by AntonelloDN** [mostaphaRoudsari/ladybug#239]
Hi all

I have made sunrise and sunset component recently and now I know  well how NOAA functions work.
haSunrise (called also **hourangle**) function is really sensible to latitude above 65°N and under -65°N.
 Thanks @saeranv, I think that LB SolarFanBasic and LB SolarEnvelopeBasic are fast and useful,  but should be great to extend the range of latitudes from about [-66°N , 65°N] to about [-89°N , 89°N]. In this way they can also work well at extreme locations such as Barrow Alaska, Kiruna Sweden.

This is what happens when you input latitude above or under values that I have written above.
![latitude_01](https://cloud.githubusercontent.com/assets/16763953/13364893/fb291634-dcd1-11e5-9eb4-968f1c37e00a.png)

I tried to delete some part of code that I think that is not useful for both components.
![latitude_02](https://cloud.githubusercontent.com/assets/16763953/13365004/d6ae3978-dcd2-11e5-87ee-f599e05a8ed8.png)
and they work good, however I would like to hear from you.
![canvas at 21 56 24](https://cloud.githubusercontent.com/assets/16763953/13365246/38cd2406-dcd4-11e5-8fa6-9289425a045b.png)

Best
Antonello

**Comment by saeranv** [comment]
Hello @AntonelloDN, I took a quick look and I believe you are correct, although I still need to test it out myself. 

I was using calculations from the NOAA for  +/- 72° latitudes (http://www.esrl.noaa.gov/gmd/grad/solcalc/calcdetails.html), but I only need the solarnoon times for my calculations, so if we can remove those extraneous calculations and still get correct results then let's remove them. 

I have some questions for you:
1. What formula are you using for your sunrise, sunset component? 
2. If it is a different formula, is it also haSunrise, or something different, and will it provide us with a solar noon time?  
 
Thank you for catching this!

**Comment by AntonelloDN** [comment]
Hi @saeranv, you're welcome

1) Basically, I started from the your same link (with NOAA_Solar_Calculations_day) , but I modified some part of it to remove the limit of accuracy and years as well.
For example, for the julian day I used a formula from  http://www.esrl.noaa.gov/gmd/grad/solcalc/sunrise.html
and I modified it by myself by adding timezone and hour for julian day. It give you the same results that you can achieve with http://www.esrl.noaa.gov/gmd/grad/solcalc/
I separated the function in three parts, because I saw that for the main part of NOAA function end with **equation of time**. Then they have to use the equation of time for sun angle or for solar noon/sunrise/sunset.
In this way, I achieved the same values of sun angles (thus sunvectors, too) and solar noon time of new NOAA suncalc http://www.esrl.noaa.gov/gmd/grad/solcalc/
And sometimes approximations errors about one-two minutes for the sunset/sunrise time for extreme locations.

2) hourangle is equals to haSunrise. The formulas are the same from **Manom** to **hourangle**, I think just the first part is different.

Antonello

**Comment by saeranv** [comment]
@AntonelloDN, just to clarify: are you saying the NOAA suncalc times for solar noon at http://www.esrl.noaa.gov/gmd/grad/solcalc/ are different from the one calculated at http://www.esrl.noaa.gov/gmd/grad/solcalc/calcdetails.html . 

I've looked at the code and the sunrise and sunset time is definitely unnecessary and I am deleting it. I am going to compare it with the other solar envelope and check to make sure they are consistent. 

S

**Comment by AntonelloDN** [comment]
@saeranv 

About Julian Day I was referring to:
"_the spreadsheets are only valid for dates between 1901 and 2099, due to an approximation used in the Julian Day calculation.the spreadsheets are only valid for dates between 1901 and 2099, due to an approximation used in the Julian Day calculation_." I changed this part using Julian Day formula of http://www.esrl.noaa.gov/gmd/grad/solcalc/sunrise.html

Although this changing, I notice that Solar noon results are the same, the main difference between these two applications should be conditional statements for sunrise/sunset. 


I'm looking forward to try your component

Best
Antonello

**Comment by saeranv** [comment]
Just sent the pull request for fixed components: #243
