### ISSUE TITLE
Add an bakeIt_ Option to Make Meshes with Image Map Materials

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/ladybug#241]
I have recently realized that most rending engines want to have the mesh colors defined as an image map.  This is the case for V-Ray, 3DSMax, and for this interesting augmented reality application that I have been playing with:
![lb_augmentedreality](https://cloud.githubusercontent.com/assets/5567574/13708554/4dd86b68-e77d-11e5-9ce8-fd21aa78de9f.jpg)

Accordingly, I am thinking of adding in an option on bakeIt_ that will automatically write out a texture image file based on the mesh colors, create a Rhino material from it, and assign the material to the baked mesh in the Rhino scene.  This way, people can render ladybug graphics with V-Ray and this should open the gateway for the incorporation of Ladybug graphics into all of the VR stuff that is getting big now.

I am not sure of the best way to allow users to specify a file path for the image but I may just do an initial pass that just writes the image to the ladybug default folder.  Anyone, please post any thoughts here.

-Chris

**Comment by mostaphaRoudsari** [comment]
[This](http://www.grasshopper3d.com/forum/topics/how-to-render-mesh-colors?commentId=2985220%3AComment%3A663243) might be helpful.

![](http://api.ning.com/files/-yI8Q9x2z*SMIJe8CBNtN3fy3NYDXa1fHm9wYwMsbqgIK4UKTvLVPUDa3j6g-oNIR6yaAJFEt3y2pVmhdm5WzhMbrjGDVMOZ/rendervertexcolors.jpg)

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Yes, I read though that conversation a few times.  There's a lot of good information on it.

**Comment by claudioarchi** [comment]
This is a great feature. Our office is starting with the vr stuff. I think that letting the user the freedom to specify a file path anywhere is the way to go. Can't wait to it
Cheers
Claudio

**Comment by chriswmackey** [comment]
When I implement this ability, I should also include a bakeIt option for vector-based text if people want to export PDFs in perspective mode:
http://www.grasshopper3d.com/group/ladybug/forum/topics/bake-options-perspective-legend-issues?commentId=2985220%3AComment%3A1492650&xg_source=msg_com_gr_forum

**Comment by chriswmackey** [comment]
Now that we have the texture-maker component, I think that our support for this workflow is good.   I'm happier with everyone being aware of where the image texture is sitting on their machines, rather than having another option built into bakeIt.
