### ISSUE TITLE
Bug? Capture View component doesn't capture

### ISSUE THREAD

**Issue by timurglobal** [mostaphaRoudsari/ladybug#244]
Hi guys,

Since Chris introduced Capture View component I grew accustomed to it and leaned a few tricks on how to make it super useful. 

Problem is, it worked flawlessly before but now it doesn't capture anything. 
I remember that before, when it worked, I had an older version of LB, then I finished my project and after a pause in a couple of months I started a new project and went ahead and updated all the user objects just to be on the safe side. So when I finally started doing screenshots I noticed that the directory folder is empty no matter what.

I've added the definition, maybe there is something wrong on my side.
[08_ShadowStudy.zip](https://github.com/mostaphaRoudsari/ladybug/files/177440/08_ShadowStudy.zip)

![bug](https://cloud.githubusercontent.com/assets/16097638/13839497/627a26dc-ec56-11e5-8900-85b01ebd76b5.png)
![empty](https://cloud.githubusercontent.com/assets/16097638/13839498/62871afe-ec56-11e5-9136-f6030ea7d04c.PNG)

**Comment by chriswmackey** [comment]
@timurglobal ,

I can't say what the exact issue is since I do not have a D:\Desktop folder on my machine but I would venture a guess that this folder does not actually exist on your system and it is just a shorthand that Windows is giving you instead of the true longer file path.  Set a file path that you have navigated to from the root of your machine D:\ and let us know if you still have the same issue.

-Chris

**Comment by timurglobal** [comment]
Hi Chris,
No, I keep all the stuff on D because it is my HDD. System and programs run from C (SSD), I just checked whether test folder in C would fix the problem but had no results there.
![canvas at 13 54 21](https://cloud.githubusercontent.com/assets/16097638/13869563/1082e358-ed11-11e5-932f-7d6dfa33c1cb.png)
It is a minor problem because I can still use Rhino's -viewcapturetofile command. anyway, I think it is still worth checking out.

**Comment by mostaphaRoudsari** [comment]
@timurglobal what is the output of the CaptureView component? ```imagePath```

**Comment by timurglobal** [comment]
Hi Mostapha,
To be honest I have no idea, should be file path, but it is always empty:
![wind rose broken legend _top](https://cloud.githubusercontent.com/assets/16097638/13899215/76ac24ce-ee23-11e5-8cfd-c36451082afc.png)
If you zoom in you will notice a weird artefact left by rhino view port's world axis (wtf).
Same happens when I use -ViewCaptureToFile, but it is easily removed by turning the feature off.
![wind rose broken legend no axis _top](https://cloud.githubusercontent.com/assets/16097638/13899233/f8d4bea2-ee23-11e5-8033-ac887557e9e9.png)

**Comment by mostaphaRoudsari** [comment]
1. Use toggle to capture the view and not button.
2. Read the [component description](https://mostapharoudsari.gitbooks.io/ladybug-primer/content/text/components/Capture_View.html) for the second issue.

**Comment by timurglobal** [comment]
1. Oh yeah, button doesn't hold the value. But it works with button and I like the feel of it, single click and done.
2. Hahaha, yeah. Usually I don't mind it, yet since I started doing hi-res captures it spammed the view a bit, still weird.
It is strange that it didn't work for shadow studies. But thanks on checking it out, I think I messed something up there. I'll check shadow study now.

**Comment by chriswmackey** [comment]
@timurglobal ,

Seeing that things seem to be resolved here, I am going to close out the issue.  Feel free to repoen if there's still more to solve.

-Chris
