### ISSUE TITLE
LB_OutdoorComfortCalculator - Last hour issue

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#250]
See this discussion:
http://www.grasshopper3d.com/group/ladybug/forum/topic/show?id=2985220%3ATopic%3A1499752&xg_source=msg
The file attached in there solves the problem. I copied/pasted the code from the LB_PMVComfortCalculator as for this discussion:
http://www.grasshopper3d.com/group/ladybug/forum/topics/pmv-calculator-warning-1-the-calculation-has-been-terminated-by
-A.

**Comment by mostaphaRoudsari** [comment]
Thanks @ayezioro! I leave this one to @chriswmackey.
I feel we haven't been involved in the same discussion for a very long time.

**Comment by ayezioro** [comment]
:-) I feel guilty ...
This one has been taken care of already. I believe we can close it.
-A.

**Comment by mostaphaRoudsari** [comment]
:)

**Comment by chriswmackey** [comment]
Ah, I forgot to close the issue.  Thank you!
So many conversations happening and so little time...
