### ISSUE TITLE
Issues with load/dump HB Objects

### ISSUE THREAD

**Issue by ocni-dtu** [mostaphaRoudsari/ladybug#253]
Hey,
When I create an HB object in one script and dump it with HBdump and try to load in another script the HBload component gives this error: "Runtime error (ImportException): No module named __main__
Traceback:
  line 71, in main, "<string>"
  line 74, in script"

My HB/LB is version 0.0.59.
The HBdump is from 25th of feb. and HBload is from 5th of feb.

I have attached my files here:
[HBZone.zip](https://github.com/mostaphaRoudsari/ladybug/files/214566/HBZone.zip)

/Christian

**Comment by mostaphaRoudsari** [comment]
Hello @ocni-dtu. Thank you for reporting this. I was not considering the case that boundary condition for adiabatic surfaces to be outdoors. This is now fixed! Try to update Honeybee and use the Honeybee_Dump Honeybee Objects components with today's date.
