### ISSUE TITLE
Have the windrose give average wind velocities for each of the segments requested by the user

### ISSUE THREAD

**Issue by TheodoreGalanos** [mostaphaRoudsari/ladybug#256]
Hi people!

I was thinking it would be helpful for wind analysis of the weather file data if we could automatically give the average wind velocity for each segment the user has specified in the Ladybug wind rose component.

From personal experience this would be very useful for CFD studies.

Thanks!

Kind regards,
Theodore.

**Comment by chriswmackey** [comment]
@TheodoreGalanos ,
I agree that this should be an output.  It should just be a few lines of code to put it in since the component already bins the wind speeds by cardinal direction.  Feel free to take a stab at putting in the code.  Otherwise, We'll get to it eventually.
-Chris

**Comment by devngc** [comment]
@TheodoreGalanos  @chriswmackey,

Implemented. Please check #323 

Thanks,
Devang
