### ISSUE TITLE
Psychrometric chart inconsistencies

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#268]
http://www.grasshopper3d.com/xn/detail/2985220:Comment:1556097

> Chris,
> thank you for the reply and the upgrade of HR ratio calculator. 
> I want you to notice some more issues:
> 1) first of all, if I connect the barometric pressure (101325 Pa used by default) to the 3D chart, it appears an error:
> 
> 
> 2) The problem with the display of the point in the 3D graph persists. Infact if I try to display the point of (x,y)=(24.05,0.006182)
> 
> 
> in the rhino 3D chart it appears in a incorrect position because the Y axis is not alligned:
> 
> 
> I can fix the starting value of humidity ratio with this:
> 
> 
> So (as you can see) it is placed in the right place:
> 
> 
> 
> Francesco

**Comment by chriswmackey** [comment]
addressed.
https://github.com/mostaphaRoudsari/ladybug/commit/c3084979946aa9c4f8c765061b27aa874135a8e9
