### ISSUE TITLE
Monthly Bar Chart component issues

### ISSUE THREAD

**Issue by stgeorges** [mostaphaRoudsari/ladybug#276]
Hi @chriswmackey ,

A couple of days ago I noticed two issues with the Monthly Bar Chart component in this topic on [grasshopper forum](http://www.grasshopper3d.com/group/ladybug/forum/topics/tof-algorithm?xg_source=activity):

1) If _inputData gets 8670 hourly values equal to 0, the component raises an error: "Attempted to divide with zero":

![monthly_bar_chart_component_error](https://cloud.githubusercontent.com/assets/4411411/17208881/c800fd1a-54ba-11e6-82f4-c5d6e07d9d4b.jpg)

I understand that "Ladybug_3D Chart" component is recommended to be used when visualization of hourly values is required, but still if Monthly Bar Chart component supports input of hourly values as well, I think it would be useful if the component will just inform the user that the inputted 8760 values are all 0, and therefor the chart can not be created.

2) Here is a screenshot of what happens when plotFromZero_ is set to True, and stackValues_ is set to False. _inputData are supplied from the Average Data component:

![plotfromzero_](https://cloud.githubusercontent.com/assets/4411411/17208928/04277a62-54bb-11e6-89c1-aa257d21b614.jpg)

Why are there missing graphAxes from the 0 to 76.22 part of the chart?

![plotfromzero_corrected](https://cloud.githubusercontent.com/assets/4411411/17208940/1a46a0ca-54bb-11e6-9fad-83a127bc4dec.jpg)

I attached an example file in here:
https://app.box.com/s/p47ghp560ow734jq0mcbe3kwwe5038em

Thank you for the reply.

**Comment by mostaphaRoudsari** [comment]
Thanks @stgeorges! I leave this for @chriswmackey to review.

**Comment by chriswmackey** [comment]
@stgeorges ,

Thank you for reporting the bugs here.  I have fixed them both with this commit:
https://github.com/mostaphaRoudsari/ladybug/commit/c60940d066d8c4118c94e4a6120ebe22539c50f8

Also, @mostaphaRoudsari , I remember you asking me a while back if the bar chart could be auto-sized when someone does not connect up an analysis period of a whole year.  This auto-sizing is present in this version that I just committed.

Cheers!
-Chris

**Comment by stgeorges** [comment]
Hi @chriswmackey ,

Thank you for the quick reply.
Maybe there was a bit of misunderstanding.
My suggestion was that when a list of 8760 values was supplied to the _inputData input, that a user gets a notice when all of them are 0, instead of raising an error: "Attempted to divide with zero". And I can see this is fixed now.

However this fix also affected the data trees. 
The older component was partially being correct on this, and would simply ignore this branch with all zeros, at least in case of monthly supplied values:

![monthly_bar_chart_component_issue](https://cloud.githubusercontent.com/assets/4411411/17421139/c9bd979c-5aa7-11e6-90e6-313cca9e2466.jpg)

However the newest component simply raises the notice that the first branch consists of all 0 zero values, and then completely stops.

Can you ignore the branches which have 8760 zero values, and plot only those that have 8760 values > 0?
For example, in upper attached TOF component for tilt angle equal to 0, the ground reflected irradiance will always have 8760 values equal to 0, while beam and diffuse irradiance would not have 8760 values equal to 0. So the Monthly Bar Chart component should ignore the ground-reflected irradiance branch where all 8760 values are 0, and plot the others branches.


And thank you for solving the issue with starting plotFromZero_!!

**Comment by chriswmackey** [comment]
@stgeorges ,
The newer component runs fine with both all-zero branches and non-zero branches as long as you set "stackValues" to True.  So you could still produce the graph that you show in your image.  The issue that I think you are encountering is that, if stackValues is not set to True and the first list in the tree has all Zeros, the chart tries to make a y-axis that goes from 0 to 0.  I realized that this is not obvious in the warning message and so I changed the warning in this case to tell the user to use LegendPar or set stackValues to True to change the Y-Axis.  I also automatically reset the chart Y-Axis to go from 0 to 1 in this case so that the component does not fail and people can get a sense of what is going on inside the component.
https://github.com/mostaphaRoudsari/ladybug/commit/a46e3f0bca1b8da1d73788cd459084c394a4012c
Here's a working file:
https://www.dropbox.com/s/mv3e5fp84769j37/Monthly_Bar_Chart_issues_CWM.gh?dl=0

-Chris

**Comment by stgeorges** [comment]
Hi @chriswmackey ,

It could be that the _stackValues has been set to False in my case.
Thank you for fixing the issue with zero values when _stackValues is set to False with [this latest change](https://github.com/mostaphaRoudsari/ladybug/commit/a46e3f0bca1b8da1d73788cd459084c394a4012c).
