### ISSUE TITLE
captureView is not taking the clippingPlaneObjects

### ISSUE THREAD

**Issue by MingboPeng** [mostaphaRoudsari/ladybug#285]
Hi Mostapha and Chris,

Is it possible to capture the objects on the rhino's clipping plane?
Thanks in advance.

Best,
Mingbo

**Comment by mostaphaRoudsari** [comment]
Hi @MingboPeng, It should capture whatever you see in Rhino viewport. What are exactly trying to do?

**Comment by MingboPeng** [comment]
Hi @mostaphaRoudsari , I was trying to make a test file to show you the problem, and it seems there is no problem of capture the "cut edge (marked on red)". But it does't work in a project file, I will try to figure out myself, and let you know later!
[image](https://cloud.githubusercontent.com/assets/9031066/17986613/8cf66a1c-6ae9-11e6-980e-a7ec4dd4d277.png)

**Comment by chriswmackey** [comment]
@MingboPeng ,
Keep us posted.  It probably has to do with a setting in your project Rhino file.

**Comment by chriswmackey** [comment]
I am going to close out this issue but please feel free to reopen it if you find it persists @MingboPeng
