### ISSUE TITLE
Change hint for LB_WindBoundaryProfile

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#287]
Hi,
I've found that for he LB_WindBoundaryProfile epwTerrain_ input, the hint should be changed from str to int. Otherwise the component gives an error (1. You have not connected a correct epwTerrain_ type.).
This is weird since the terrainType_ input works fine with the str.
Thaks,
-A.

**Comment by chriswmackey** [comment]
Thanks for finding the issue with the EPW Terrian type, @ayezioro .

I have fixed it here so that it can now accept either the integer or the text name of the terrain:
https://github.com/mostaphaRoudsari/ladybug/commit/db04953c4511fad3b302ec01c18fa71231bdb712
