### ISSUE TITLE
please let the ladybug fly

### ISSUE THREAD

**Issue by alsheekhli** [mostaphaRoudsari/ladybug#295]
can you help in solving this problem as after i loaded the date, theer was a  warning please let the ladybug fly on its icon. need  some help to figure it out ?

**Comment by mostaphaRoudsari** [comment]
You need to drag and drop ladybug_ladybug component into Grasshopper canvas. Check the [Grasshopper forum](http://www.grasshopper3d.com/group/ladybug/forum)!
