### ISSUE TITLE
Pull Bioclimatic Chart Out of WIP [Enable Alternate Display Types for Psychrometric Chart]

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/ladybug#304]
Including Operative Temperature, Relative Humidity Chart, and (perhaps) Bioclimatic Chart (because it is so close to the Relative Humidity Chart and I have been looking for a reason to fuse efforts with @ayezioro ).  All of this is mentioned in this discussion:
http://www.grasshopper3d.com/group/ladybug/forum/topics/ladybug-psychrometric-chart-customization-as-in-cbe-thermal?commentId=2985220%3AComment%3A1617144&xg_source=msg_com_gr_forum

This is all such a big task that I might not get around to it until I do the revision of the code for the new Ladybug.  Still, I 'm putting it here for the record.

-Chris

**Comment by ayezioro** [comment]
Yes.
I want to discuss with you how to finally get the bioclimatic component out of the WIP. Maybe i'm having difficulties seeing this differently from how i'm used to. So i'm for joining efforts here.
I need some time to be able to retake this task, but in a month or so i think i'll be back here again.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

I had a thought that maybe we should take your component out of WIP now.  It was never for a lack of usability that we kept it in there if I remember.  It was just that we wanted to have the comfort polygon derived from a PMV model as opposed to the rules of thumb, which is only relevant to some cases an not others.

Given that I want to do a whole re-vamping of the psych chart for the new Ladybug (adding Operative Temperature, making the calculation of comfort polygon faster, allowing people to plot polygons for UTCI and PET models, etc) maybe we wait to fully join forces then.  So, for the current Ladybug, we leave the components as they are and we start afresh in a clean coordinated manner.

Let me know your thoughts when you get the chance and there's definitely no rush on this.  If we decide to do it for the new Ladybug, it will be a long process but it should hopefully help ensure that we implement it well.

-Chris

**Comment by ayezioro** [comment]
Hi @chriswmackey ,
Agree with all you wrote. The functionality of the bioclimatic chart is based on rules of thumb, and i am much for something more robust, so i'm fine with your proposal.
So in a few weeks i'll get back here to start the process.
-A.

**Comment by chriswmackey** [comment]
The component was moved out of WIP via https://github.com/mostaphaRoudsari/ladybug/commit/54939bd93adced4d87576443b180586f1ab58bb8

Closed!
