### ISSUE TITLE
Issue with the saving of the data of the .epw-file for creating the cumulative sky matrix  

### ISSUE THREAD

**Issue by MauroLuzzatto** [mostaphaRoudsari/ladybug#305]
I would like to report an issue with creating the cumulative sky matrix for weather files of different years from the same location with Ladybug. The component `Ladybug_GenCumulativeSkyMtx` creates a sub-directory with a copy of the `.epw` file, which is set as input to the component, in the default folder `Username\AppData\Roaming\Ladybug\`. The component uses now the .epw-file from this location to calculate the sky matrix. If I now want to use a different `.epw` input file of the same location but from a different year, the saved copy of the old `.epw` file is loaded from `Username\AppData\Roaming\Ladybug\`. This is because only the location name is read from the Ladybug-component and therefore Ladybug expects the files to be equal. To make sure different `.epw-files` can be read in Ladybug, the component should check what year the data in the `.epw-file` is from. I would propose to add the year of the used `.epw-file` in the folder directory name, to make sure different yearly data is not mixed for the calculation of the cumulative sky matrix.

Old Code:

```
# import data from epw file
locName, lat, lngt, timeZone, elev, locationStr = lb_preparation.epwLocation(epwFile)
newLocName = lb_preparation.removeBlank(locName)
```

New Code: 
Added year to the new location name, where the .epw-file is going to be saved: 

 1.) Read first line of epw-file and read the specific year (line 140 to 143)

```
epw_file = open(epwFile,"r")
for lineCount, line in enumerate(epw_file):
year = (line.split(',')[0])
epw_file.close()

```

2.) Add year as string to the location name (line 176 to 178)

```
# import data from epw file
locName, lat, lngt, timeZone, elev, locationStr = lb_preparation.epwLocation(epwFile)
newLocName = lb_preparation.removeBlank(locName + "_" + str(year))
```

Best, Mauro Luzzatto

**Comment by chriswmackey** [comment]
Thanks for catching this @MauroLuzzatto . I didn't realize that this error could exist for some weather file locations here.  The fix has been implemented;
https://github.com/mostaphaRoudsari/ladybug/commit/364f5f1e43561965e4fc3ab7b3feb153fc026abf
Thanks again!
-Chris
