### ISSUE TITLE
Update error - 'UOYear' referenced before assignement

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/ladybug#314]
Hello,

while trying to update a ladybug definition I got this error.
I even tried to replace manually all the ladybug's components I had on the canvas but the error doesn't go away.

![image](https://cloud.githubusercontent.com/assets/8501837/19960033/ad72f808-a1aa-11e6-8794-7cb6e55867d2.png)

**Comment by mostaphaRoudsari** [comment]
@jacoposartore sorry for the delay! I just saw this. Is this still there? I can't recreate the issue.

**Comment by jacoposartore** [comment]
I tried today and now it's working! Thanks!
