### ISSUE TITLE
Ladybug Shading Mask II not outputting maskedSkyDome

### ISSUE THREAD

**Issue by devngc** [mostaphaRoudsari/ladybug#320]
Hi @mostaphaRoudsari,

While looking into [this](http://www.grasshopper3d.com/group/ladybug/forum/topics/shading-mask-component-does-not-run?xg_source=activity) query, I noted that the Ladybug_Shading Mask II component is not outputting anything from its maskedSkyDome output. Without this, the user is not able to color the shadedSkyDome as I have done in the image below.

I have created #319 that fixes this bug.

Devang

![shading masks](https://cloud.githubusercontent.com/assets/20086924/20260573/4b096bfa-aa80-11e6-9cbb-d2243854ee5b.jpg)

**Comment by AntonelloDN** [comment]
Hi @mostaphaRoudsari and @devngc 

probably, this advice could help to reach the right number of surfaces
![advice](https://cloud.githubusercontent.com/assets/16763953/20432030/9003fe12-ad9d-11e6-9591-6bcc2cd2de7d.png)

Sometimes the current fold of the sky splits the projected surface. Xaxis as axis of revolution should solve this.

P.S. sorry for my ugly sketch! XD

**Comment by devngc** [comment]
Hi @AntonelloDN,

So cool of you to send a sketch. I think this is a great idea to generate a seamless skyDome. Very useful advice.

Thanks,
Devang

**Comment by devngc** [comment]
I took your advice seriously @AntonelloDN. It was an astute observation. Thanks again!
