### ISSUE TITLE
Tiny bug for "Window Downdraft" component

### ISSUE THREAD

**Issue by stgeorges** [mostaphaRoudsari/ladybug#322]
Hi @chriswmackey ,

I just noticed that Ladybug ```Window Downdraft``` component has two lines missing:
```
import Grasshopper.Kernel as gh

w = gh.GH_RuntimeMessageLevel.Warning
```
before raising the warning.

**Comment by mostaphaRoudsari** [comment]
@stgeorges thanks for reporting! Why don't you go ahead and send a PR for this one? :)

**Comment by stgeorges** [comment]
Ok. I opened a new pull request in here:
https://github.com/mostaphaRoudsari/ladybug/pull/324

**Comment by mostaphaRoudsari** [comment]
Thanks! merged!

**Comment by chriswmackey** [comment]
Thank you for fixing this @stgeorges !

**Comment by stgeorges** [comment]
Thank you guys!
