### ISSUE TITLE
Add  Beafourt scale to windrose

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#327]
Following up from the conversation [here](https://github.com/mostaphaRoudsari/ladybug/pull/323#issuecomment-262689187) started by @ayezioro:

hi @devngc ,
Thanks for this. I have though a new challenge for you, unless you tell this is doable:
There are some requirements regarding % of time that you can allow for considering the wind as usable and/or dangerous. For instance, for mechanical reasons, annual average beyond 1% at (say) 20 m/s is considered dangerous and as such you have to address the issue. There are different requirements for different velocities, as i said, some are related to the mechanical influence of the wind and others for comfort reasons.
You think it is doable here if you already get the averages?
Thanks,
-A.

**Comment by chriswmackey** [comment]
In @devngc 's recent pull request, the Beafourt scale component was placed in the visualize weather data tab, where it really does not seem to fit:
![misplacedbeaufort](https://cloud.githubusercontent.com/assets/5567574/20869419/f48b0458-ba3f-11e6-90a0-865915861df9.JPG)

I feel that it is better placed in the Extra Tab next to the comfort parameter components:
![comfortparametercomps](https://cloud.githubusercontent.com/assets/5567574/20869413/e6ce8a92-ba3f-11e6-9571-578bdf35b9d1.JPG)

**Comment by devngc** [comment]
@chriswmackey,

Noted. I have no problem with that. Will do that when I initiate a PR.

Thanks,
-Devang

**Comment by devngc** [comment]
@mostaphaRoudsari,
This was addressed in #330. Can be closed.
Thanks,
-Devang

**Comment by chriswmackey** [comment]
@devngc ,
I've tested the new component on my system and all looks great.  Let's close this one out!
