### ISSUE TITLE
Wind Rose Feature Requests

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/ladybug#328]
This is continuing [a thread here](https://github.com/mostaphaRoudsari/ladybug/pull/323#issuecomment-264710180) where I listed a bunch of feature requests for the new wind rose.  These include:

1. Provide an output of average wind velocities and frequencies as lists for all directions.
2. Produce wind velocities and frequencies for all acceptable directions.
3. Keep offset for average velocities and frequencies permanent and remove offset inputs for wind velocities and frequencies.

-Chris

**Comment by devngc** [comment]
@chriswmackey,

I have incorporated all those features. I am currently testing the component. Will share the same with you for a review soon.

Thanks,
Devang

**Comment by chriswmackey** [comment]
Ok.  Sounds great!

**Comment by devngc** [comment]
@chriswmackey,

Please find snap shots and [sample file](https://github.com/devngc/Work-in-Progress/blob/master/WindRose_R1.gh) for wind rose component with your specifications incorporated.

1. Beaufort Ranges Connected
![beaufort range](https://cloud.githubusercontent.com/assets/20086924/20869061/8f7efda2-ba90-11e6-8411-9b03c0daa1ff.jpg)

2. Regular  Conditional  + Analysis Period
![regular conditional analysis period](https://cloud.githubusercontent.com/assets/20086924/20869063/9f5ea966-ba90-11e6-9d02-dd2d721d37fc.jpg)
 
Thank you!
Devang

**Comment by chriswmackey** [comment]
@devngc ,
This is absolutely awesome!!!!  Thank you so much for adding all of this in so quickly.
As far as I can tell from playing around with the file, everything has been addressed so please send a pull request whenever you get the chance and I will merge it in and close out this issue.
-Chris

**Comment by chriswmackey** [comment]
@devngc ,
I was going to close out this issue as a result of [your recent pull request](https://github.com/mostaphaRoudsari/ladybug/pull/329#issuecomment-264732291) but I realized that your updated userObject in your pull request does not seem to be the same one in the example file you uploaded here.

Please send another pull request with the correct userObject and then we can close out this issue.
-Chris

**Comment by devngc** [comment]
Thank you @chriswmackey,

You also suggested we group outputs together. I tried doing that too. Once I did that, the component stopped showing the legend. (It would show if output of legend were provided to Gh preview component.) without giving any error. I spent some time on that but could not find the reason for that behavior. So eventually, I just added new outputs and did not group them.

You may also note that I am pushing the text title (the text below the wind rose) to make room for the radial display of average wind velocities and frequencies. When other EPW data is attached to annualHourlyData_ and new wind roses are generated, in those wind roses, the text titles get pushed to a distance greater than the first wind rose. This is something I still need to figure out. Therefore, for the time being, I have set up some limitations. If you connect EPW data to annualHourlyData_ , wind rose will go back to its classic form.

Thank you for your time,
Devang

**Comment by chriswmackey** [comment]
@devngc ,

With regards to reorganizing the outputs, the reason why some of the outputs are hidden is a result of this code:
https://github.com/mostaphaRoudsari/ladybug/blob/master/src/Ladybug_Wind%20Rose.py#L896-L897
You will need to change the index specified to ensure that the right outputs are displayed or hidden.

I see what you mean about the other issue but it's pretty minor in my mind.  To address it, you just need to send the frequency/speed labels into the calculateBB function here:
https://github.com/mostaphaRoudsari/ladybug/blob/master/src/Ladybug_Wind%20Rose.py#L460
Again, I see this as pretty minor right now so it's cool by me if it's not in the next PR.

Keep up the great work and I'm looking forward to the updates!
-Chris

**Comment by devngc** [comment]
Thanks a lot @chriswmackey!

I could address the grouping of outputs. The code you pointed out to was very helpful. The second limitation is still in place. I will need to look deeper to lift this limitation. Will work on the same.

Thank you for help!
-Devang

**Comment by devngc** [comment]
@chriswmackey,

The limitation has been lifted. Please find image attached. Sample file can be found [here.](https://github.com/devngc/Work-in-Progress/blob/master/WindRose_R2.gh)

Beaufort + Conditional Statement+ Analysis Period + Annual Hourly Data
![beaufort conditional analysis period annualhourlydata](https://cloud.githubusercontent.com/assets/20086924/20899616/1d03afae-bb51-11e6-9f9a-c38bd19e9fee.jpg)

I have created #331  to push these changes.

Many thanks,
-Devang

**Comment by chriswmackey** [comment]
@devngc ,
Now that all issues are addressed, I think we can close this one out.  Thanks again for all of your hard work!

**Comment by devngc** [comment]
@chriswmackey,
Thank you! Always a pleasure.
-Devang
