### ISSUE TITLE
Ladybug_False Start Toggle: Loading Error

### ISSUE THREAD

**Issue by devngc** [mostaphaRoudsari/ladybug#337]
Hi @AndrewHeumann, @mostaphaRoudsari,

On loading the new Ladybug_False Start Toggle, I receive this error. Is this happening to me only?

![screenclip](https://cloud.githubusercontent.com/assets/20086924/21380802/a3f44c52-c77d-11e6-80cf-75317f6d0992.png)

Thanks,
-Devang

**Comment by mostaphaRoudsari** [comment]
@devngc you need to install the toggle itself first by copying the [gha file](https://github.com/mostaphaRoudsari/ladybug/blob/master/userObjects/FalseStartToggle.gha?raw=true). Ladybug update doesn't copy GHA files for you.

Don't forget to unblock the file after downloading.

**Comment by devngc** [comment]
@mostaphaRoudsari,
Thanks a lot. It works now.
