### ISSUE TITLE
No colours showing when generating a sun path and reference points

### ISSUE THREAD

**Issue by RenzoJA** [mostaphaRoudsari/ladybug#338]
Hi I'm not getting any colours when running the workflow mentioned above. I'm using Dynamo 1.2. I have also tried to run the same definition on other computers but still can't get colours to come through. Thanks

**Comment by mostaphaRoudsari** [comment]
Hi @RenzoJA! You should have posted this issue to https://github.com/ladybug-analysis-tools/ladybug-dynamo/issues but in any case can you provide more details? Does it give you any error message from `report` output?

**Comment by chriswmackey** [comment]
Given that there was no response here, I'm going to assume that the conversation continued over on the Ladybug-Dynamo repo.  Feel free to reopen the issue if I'm wrong.
