### ISSUE TITLE
commit "Stereograhpic and Orthographic Projections Added to Sun Path"

### ISSUE THREAD

**Issue by Vyrwn** [mostaphaRoudsari/ladybug#345]
@chriswmackey,

first of all thank you for adding these options and even more thank you for adding my name to the credits.

I just had a quick look and I have a comment for the angle crvs. I see in the code that you have it marked as done in last minute and to be improved, but there is a problem with the angle curves of the stereographic sunpath.

The angles shown now are of an "equidistant" sunpath. The distance between each angle curve is remaining the same, which is not the case on the stereographic sunPath. I can see in your code that you are calling the curves from the main LB component and I did not have time to go further into it.

If you see my code that I sent you last week I am creating the angle curves by projecting with the same stereographic principal.

Let me know if you want me to have a look in the original code and do the change myself.

-Byron

**Comment by chriswmackey** [comment]
@Vyrwn ,
Thanks for catching this.  I was looking at your file while integrating the new code but I did not realize that the angle curves for the stereo projections were not equi-distant.  I wanted to calculate the radius of the curves based on a mathematical formula as this is faster than using the projection function (although the speed increase is admittedly not really noticeable).  In any case, I checked back on the stereographic wikipedia page and I have fixed the issue with this commit:
https://github.com/mostaphaRoudsari/ladybug/commit/da669e7c2d78fdc0f5eb58a35df7ea2aea218a40

Thanks again,
-Chris
