### ISSUE TITLE
Contour Mesh suggestion

### ISSUE THREAD

**Issue by nildan** [mostaphaRoudsari/ladybug#348]
Hi!
Love your work here, thanks for doing all this great stuff. I  played around a little with the new Contour Mesh component – it's great. Really useful for making nice visualizations.

An additional thing I would like to do, however, is to show only some of the contour lines  – for example highlighting the 1 % line in a daylight factor simulation. An output that makes it possible to cull the lines based on their values could fix that – would that be possible?

Also, contourLines outputs both lines and labels for me, whereas contourLabels is empty. Is that a bug?

Thanks!

Kind regards,
Daniel

**Comment by chriswmackey** [comment]
@nildan ,

I'm glad to hear that you like the new component.  The type of visualization that you are talking about is relatively straightforward to set up by post-processing the results from the contour mesh component.  You probably want to use the legendPar to get the contour lines to land right on your threshold then use the List Item component to select out the meshes that you want to display.  You can find an example below:
![select countour mesh](https://cloud.githubusercontent.com/assets/5567574/22634801/bc88ce30-ebfb-11e6-900e-d542d42e0497.JPG)
https://www.dropbox.com/s/zspz22iawyso8oo/ContourMeshExample3.gh?dl=0

Also, the lack of output from the countrouLabels was a bug that I have just fixed. 
https://github.com/mostaphaRoudsari/ladybug/commit/65c4198b055836ceb6cd289d70a1761bb045f6af
Thanks for finding and reporting it!

-Chris

**Comment by nildan** [comment]
Thanks Chris, I didn't realise this. So, this example does pretty much what I want:

[https://www.dropbox.com/s/d98deud51bxr4jf/contour%20mesh%20question.gh?dl=0]

Two quick questions though:

1) Why doesn't the lowest value meshes (<0,4) show up by default in this case?
2) Inputting _contourType 1 or 3 gives an error now. Bug?

Thanks,
Daniel

**Comment by chriswmackey** [comment]
@nildan ,
Whenever you see holes in the mesh or a certain surface not showing up, it's the result of the fact that your analysis grid is not fine enough for the number of contours that you are specifying.  In other words, the Rhino intersection calculation that makes the contours is failing.  In your case here, you can either re-run your analysis with a finer grid or decrease your number of contours (as I have done here)  to go from this:
![image](https://cloud.githubusercontent.com/assets/5567574/22810681/4639c544-ef08-11e6-9be2-d1f0862cd692.png)
to this:
![image](https://cloud.githubusercontent.com/assets/5567574/22810712/67ceb7aa-ef08-11e6-97f0-2a572fcd10c8.png)

Any, YES!  That was a bug created from the last fix that I just did.  It's all good now:
https://github.com/mostaphaRoudsari/ladybug/commit/a7223762eadc5d16219f6be3d7e02c5b0c976e88
Thank you for catching that before our stable release!
-Chris

**Comment by nildan** [comment]
OK, I understand. Thanks, now it works!

-Daniel
