### ISSUE TITLE
LB Radiation analysis component [disFromBase] error

### ISSUE THREAD

**Issue by Omidmr** [mostaphaRoudsari/ladybug#350]
Hi @chriswmackey , 
LB Radiation analysis component [distance From Base] input, doesn't accept geo.
![image 4](https://cloud.githubusercontent.com/assets/11173265/22678050/8195b754-ed0c-11e6-9ca4-b6c93723ca73.png)

""
Current document units is in Meters
Conversion to Meters will be applied = 1.000
Runtime error (MissingMemberException): 'Guid' object has no attribute '__float__'
Traceback:
  line 269, in main, "<string>"
  line 493, in script
""
reference:
http://www.grasshopper3d.com/group/ladybug/forum/topics/strange-error-with-ladybug-radiation-analysis-following-update?xg_source=activity

Kind regards,
Omid.

**Comment by devngc** [comment]
@Omidmr Can you please elaborate why you are providing a geo to this input? Can you not provide a float?

**Comment by Omidmr** [comment]
Hi @devngc ! thanks. It's not my personal issue. I agree with you with float & number.
Btw, I think it can be useful sometimes. or for the specific purpose.

best,
Omid.

**Comment by mostaphaRoudsari** [comment]
Hi @Omidmr! I also commented in grasshopper group but probably here is a better place to discuss this. Are you proposing an option to use a different geometry to create the test points? I'm not sure if this is a bug report or a feature request.

**Comment by mostaphaRoudsari** [comment]
I think I know what is the issue now. The input type hint is missing.

**Comment by Omidmr** [comment]
Hi @mostaphaRoudsari, Thanks for the reply. 

I think it's interesting as the second option for creating test points with surface instead number ( by that can will be cull unwanted areas of surfaces for analysis).
I'm trying for preparing an option for that.
best.

**Comment by Omidmr** [comment]
Thanks, @chriswmackey, Currently I think it's no need another option for creating test points.
Until I write that. I close this.
Thanks again.
