### ISSUE TITLE
Ladybug_Create Legend component suggestion

### ISSUE THREAD

**Issue by marios-tsiliakos** [mostaphaRoudsari/ladybug#354]
In order to incorporate the case where the same **base point** for the legend is provided by both the legend params component.
*you can add the following line:*

`if legendBasePoint == None and legendBasePt_ != None: legendBasePoint = legendBasePt_
elif legendBasePoint != None and legendBasePt_ != None:legendBasePoint = legendBasePt_
else: legendBasePoint =  @rc.Geometry.Point3d(0,0,0)`

*Just a suggestion*

Best,
M

**Comment by chriswmackey** [comment]
Thanks for catching this @marios-tsiliakos . Done!
https://github.com/mostaphaRoudsari/ladybug/commit/90a4fbe75c8455b27f8579c8bb01bc685fb35c08

**Comment by marios-tsiliakos** [comment]
Sweet. Thanks @chriswmackey .
