### ISSUE TITLE
Graft the result output from the realTimeRadiation Analysis

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#36]
Thanks to Abraham:
http://www.grasshopper3d.com/group/ladybug/forum/topics/surface-problem?commentId=2985220%3AComment%3A960618&groupId=2985220%3AGroup%3A658987

**Comment by chriswmackey** [comment]
I think this is really not so helpful at the end of the day.  After all, if you really need this functionality, you can graft the surfaces going into the radiation study to get two separate intersection matrices.  For this reason, I am closing out this issue.
