### ISSUE TITLE
shadingMask orientation angle inconsistency

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#362]
Hi,
For the orientation_ input there is a discrepancy between numerical angles of this component and others.
For instance 90 (supposed to be east) performs as west. For Sunpath component 90 is east, 270 west, etc.

Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

I see what you mean here.  My original thought was to keep the orientation numbers synced with that of the "north" input of the sky visualization components, which all rotate the sky counter-clockwise when you put in a number.  But you are right that this gets confusing when the "30" mark on the sunpath does not correspond with a surface facing it.  I have fixed this here:
https://github.com/mostaphaRoudsari/ladybug/commit/bb1925e3ccc96d254491582e9e6b5bd972da5f75

Thanks for pointing this out!
-Chris

**Comment by ayezioro** [comment]
100%
Thanks once again!!
-A.
