### ISSUE TITLE
Correcting sun angles for the influence of north direction angle

### ISSUE THREAD

**Issue by stgeorges** [mostaphaRoudsari/ladybug#364]
Hi @twastvedt ,

I understand that it's been a long time since you contributed to the Ladybug repository, but I was wondering if you could help me with one issue:
I would like to use the [Sunpath.solInitOutput](https://github.com/mostaphaRoudsari/ladybug/blob/master/src/ladybug_ladybug.py#L1494) method which you wrote for the ```Ladybug_Ladybug.py``` file.
I will be using it to get sun zenith, altitude and azimuth angles (self.zenith, self.solAlt, self.solAz in your method).
However I would like to calculate these three variables in accordance to the ```self.angle2North``` variable defined in the [Sunpath.initTheClass](https://github.com/mostaphaRoudsari/ladybug/blob/master/src/ladybug_ladybug.py#L1483) method above.
Did I understand correctly that self.zenith and self.solAlt variables will never be affected by the change of ```self.angle2North```, while final self.solAz variable from your ```Sunpath.solInitOutput``` method will have to be corrected as: 

```final_solAz = self.angle2North + self.solAz```?

I am not asking you to change anything from your method, I am just asking how can I correct the upper mentioned three sun angles for the influence of the ```self.angle2North```.

Thank you in advance for the reply.

Regards,
Djordje

**Comment by chriswmackey** [comment]
@stgeorges ,

Perhaps we might get a response from @twastvedt here but I know that he wrote the code a long time ago and the function that you are referring to is actually an amalgamation of @mostaphaRoudsari 's original function (derived from the Radiance sunpath), @twastvedt 's function that he originally wrote for "Colored Sky Visualizer" component, and some patchwork that I did to get these two to work together.  Needless to say, I think that it's been such a long time for all of us that we forget the answer to your question and we would have to go back to the code to understand what we did.  It seems like you were able to figure out what we did according to your recent pull request:
https://github.com/mostaphaRoudsari/ladybug/pull/363

If this is true, please feel free to close out the issue.  We will be sure to document all of the code much better when we revise everything for Ladybug[+] and this will help avoid confusion about the different variables.

-Chris

**Comment by stgeorges** [comment]
Hi @chriswmackey ,

Thank you for the quick reply and detailed clarification!! I envy your memory to remember where particular methods came from and how did they change during time.
The https://github.com/mostaphaRoudsari/ladybug/pull/363 pull request may still not fixed all the things with the upper mentioned sun angles and north direction angle.
I would be very grateful if this issue would remain open, maybe Trygve will chime in with some additional info. I would like to be certain that I implemented the right correction.
Once again, thank you for the help.

**Comment by twastvedt** [comment]
Hi Djordje! (and Chris!)
Wow, it has been a while. Thanks for reaching out. I think it will be safest if I don't speak to specifics of the code as, like Chris, I don't remember how it all went down. I can speak with some certainty about the parameters though, as those aren't specific to the way we implemented the calculations.

- Yes, the calculation of the sun's altitude will not be affected by the site's rotation.
- Is `self.zenith` just `pi/2 - self.solAlt`? If so then yes, it will be similarly unaffected by the site's rotation.
- Yes, the equation you have for modifying the azimuth angle looks correct to me. The only thing I'd be concerned about is the sign of `self.angle2North` in the equation, but you can very easily test that.

**Comment by stgeorges** [comment]
Thank you for the quick reply @twastvedt !

Can you just be a bit more specific on this part please:
> The only thing I'd be concerned about is the sign of ```self.angle2North``` in the equation, but you can very easily test that.

**Comment by twastvedt** [comment]
I'm not sure if `final_solAz` should be `self.angle2North + self.solAz` or `-self.angle2North + self.solAz`, but for large values of `self.angle2North` it should be easy to distinguish which of the two equations is correct as you'll already have an idea of roughly what the value of `final_solAz` should be based on common sense.

**Comment by stgeorges** [comment]
Thank you for the clarification Trygve!!
