### ISSUE TITLE
Contour Mesh

### ISSUE THREAD

**Issue by nildan** [mostaphaRoudsari/ladybug#368]
Hi!
I did some testing of the Contour Mesh component prior to the last release, and after having used it for a while now, I have a few comments:

1) Again, it's great! Really, in my book this opens up a whole new set of visualisation possibilities for Ladybug. Thanks for adding it.
2) I've found that the question I had before, that depending on the mesh and values it sometimes doesn't fill the entire mesh with colours, is actually a problem. Since I want to have a consistent legend across different meshes (rooms in my case) and across projects, I cannot play around with the settings to find out what works in each individual case. See this file for an example – it works nicely for one room, OK for another and not so good for a third: [https://www.dropbox.com/s/7a83oc7w82lqbpg/contourmesh.gh?dl=0](https://www.dropbox.com/s/7a83oc7w82lqbpg/contourmesh.gh?dl=0)
3) When baking the results, the legend scale changes – see the example with baking turned on. It doesn't seem to affect the meshes though.

Keep up the good work :)

Daniel

**Comment by chriswmackey** [comment]
@nildan ,
I have some ideas about how to make the contour mesh more reliable and I will try to add them soon.  I have noticed that the Rhino intersection will fail in in the portions of the mesh where it is a single repeating value.  Thankfully, putting a colored mesh with the recolor mesh component beneath the contour mesh usually addresses this well.
I'll post back here once I build this into the component.

**Comment by nildan** [comment]
Sounds great. Thanks!

**Comment by yehezkielwm** [comment]
Hi! 

The contourMesh is an amazing tool. I encounter this error while trying to contour the mesh. Please refer to the image and dropbox link below for the GH file.  

![image](https://cloud.githubusercontent.com/assets/26462602/24000589/eca1fea6-0a5b-11e7-9554-62de98ba6bbd.png)

https://www.dropbox.com/s/870kr2l9re3wuco/contourMesh%20holes.gh?dl=0

**Comment by nildan** [comment]
Sorry for asking about this again, but is there any update on this issue?

Sometimes I also get another result, with overlapping meshes. This seems to happen with finer grids, but also somewhat randomly, not for every mesh with that resolution. Any ideas how this could be solved?

![image](https://cloud.githubusercontent.com/assets/25552268/25218855/a82388dc-25ac-11e7-81fa-2458483778d5.png)

**Comment by chriswmackey** [comment]
@nildan ,
Sorry for the late response on this.  I'm going to try to work in my new ideas now and, if I don't finish today, they should be done sometime this weekend.

**Comment by chriswmackey** [comment]
@nildan ,
I added some of the ideas that I had mentioned and I've made it a little bit more robust:
https://github.com/mostaphaRoudsari/ladybug/commit/6f61109f722949bbd70d701c0d307a9c7e4c2f9e
However, the component is still not as reliable as I would like it to be.  It seems to be really hard to write checks for when the Rhino intersection calculation fails.  I wish Rhinocommon API would just return failure if it cannot do the intersection perfectly instead of returning bad meshes.  If I think of a better way to check this specific type of bad mesh, I can make it reliable.  I'll keep you posted if I think of anything.
-Chris

**Comment by chriswmackey** [comment]
@nildan,
I figured out how to detect when the intersection fails and I wrote in some code to take out these bad meshes:
https://github.com/mostaphaRoudsari/ladybug/commit/3cc2cdddb9670ebb2107d78a4114f08c8dc6fbf5
Unfortunately, there is no way to fix failed intersections for good with Rhino 5 and the best that I can do now is take them out and use an underlay to cover up the failed portions.
Maybe McNeel will solve this in Rhino 6 but, for now, the component is as good as it's possible to get.

**Comment by nildan** [comment]
Thanks @chriswmackey, great work! I'll try it out in my upcoming projects – hopefully it solves most of the problems until Rhino 6 is here.
