### ISSUE TITLE
sunlightHoursAnalysis - _disFromBase

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#369]
Hi,
My understanding until now, is that the resulting mesh for this component should be offseted according to the _disFromBase input.
The test points are, but the mesh itself remains in the same place as the geometry input.
Is my understanding wrong?
Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
Hi Abraham, The mesh stays as the original surface. Only the test points are moved not to intersect with the original surface/mesh.

**Comment by ayezioro** [comment]
OK. Thanks Mostapha.
Was just wondering. Something inb the description of the input is also (kind of) misleading:
> If the resulting mesh of this component is offset to the wrong side of test _geometry, you should use the "Flip" Rhino command on the test _geometry before inputting it to this component.

All good now.
Thanks again,
-A.

**Comment by mostaphaRoudsari** [comment]
I agree that it can be misleading. cc: @chriswmackey

**Comment by chriswmackey** [comment]
@ayezioro ,

Thank you for pointing this out and I apologize for responding so late.  I have fixed the component descriptions here:
https://github.com/mostaphaRoudsari/ladybug/commit/90937cf95699ffd8b99af0476d47e022cd9f40c5

-Chris

**Comment by ayezioro** [comment]
Thank you!
Not a biggie.
-A.
