### ISSUE TITLE
Ladybug 3D chart: adjust some details

### ISSUE THREAD

**Issue by frank984** [mostaphaRoudsari/ladybug#377]
Hello.

If the series of hourly data is not a multiple value of 24 hours, the horizontal lines of the graph curves are truncate to the previous full day. It could be better if the line completely fills the graph.

1. If I use the LBHeader and I define the unit, for example [°C], in the header I found something like this: ([°C]). 
2. If I exclude the square brackets and then in the unit I input only °C, in the upper limit of the legend I find °C and not (°C). So I think It would better to standardize the visualization of the u.m. in the graph with all the parenthesis (preferably square brackets).

![c9055fd0-d980-11e6-92a7-e8be7a4f7b59](https://cloud.githubusercontent.com/assets/6491927/24454705/2657296a-148d-11e7-8987-079b5815db99.JPG)

**Comment by frank984** [comment]
The same considerations about psychrometric chart:
For a direct use of image output, it could be better if the unit of measure are expressed in both x and y axis , passing from this version:
![1](https://cloud.githubusercontent.com/assets/6491927/24454962/306df4f0-148e-11e7-9c08-518b0a88f993.jpg)
to this:
![1_r1](https://cloud.githubusercontent.com/assets/6491927/24454965/382c8620-148e-11e7-8461-16c13f7cb170.jpg)

**Comment by chriswmackey** [comment]
Thanks for the suggesion, @frank984 
3D Chart has been addressed via:
https://github.com/mostaphaRoudsari/ladybug/commit/cfa068820affb56b89adccdc9ccd0bfab7204417

Psych chart has been addressed via:
https://github.com/mostaphaRoudsari/ladybug/commit/22dec067ff2e044d399bb01e3c9613700665bd8a
