### ISSUE TITLE
download stat and epw doesn't work with onebuilding links

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#384]
http://www.grasshopper3d.com/forum/topics/weather-file-not-downloading?xg_source=activity

@chriswmackey I wanted to fix this myself but then saw you're taking care of old DOE links too. I think we can remove it now as everyone should have updated their links by now or they should if they haven't done it yet!

**Comment by chriswmackey** [comment]
Fixed!
https://github.com/mostaphaRoudsari/ladybug/commit/08feff2678018c2f4c6a5a0a55e59a11bd6c644f
