### ISSUE TITLE
Contour Mesh Colours

### ISSUE THREAD

**Issue by twanito** [mostaphaRoudsari/ladybug#385]
Hi, I've been trying to export a contour mesh to the Spectacles Scene compiler and noticed that the contourColors output is always set to "Black" despite the colours appearing on the rhino preview and on the mesh. Think it's a minor bug.

**Comment by chriswmackey** [comment]
@twanito ,
I am not able to create what you are talking about on my end:
![image](https://cloud.githubusercontent.com/assets/5567574/25600128/e9be2aac-2eaf-11e7-8088-915a90c10e56.png)
Could you post an example?

**Comment by chriswmackey** [comment]
Ah, I see what you mean.  The contourColors are meant to refer to the color of the lines when you choose the "3 - Colored Lines" _contourType_.  This is just left black when "3 - Colored Lines" is not selected as I would think people would like black contours.  However, I realize this is not so useful so I've changed this to correspond to the contourMesh here:
https://github.com/mostaphaRoudsari/ladybug/commit/3cc2cdddb9670ebb2107d78a4114f08c8dc6fbf5

**Comment by twanito** [comment]
Thanks for the quick patch!
