### ISSUE TITLE
LB_radiationAnalysis - Baking issue

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#386]
Hi,
As for this discussion:
http://www.grasshopper3d.com/group/ladybug/forum/topics/ladybug-radiation-analysis-bake-error-projectname-is-not-defined?commentId=2985220%3AComment%3A1743469&xg_source=msg_com_gr_forum
the radiationAnalysis complains about "1. Solution exception:global name 'projectName' is not defined".
It happens in line 192.
If you change this line to "projectName_" (at the end) instead of "projectName" it works.
Didn't check other components that might have similar problem when the bake option is requested.
Thanks,
-A.

**Comment by shahiz** [comment]
Thanks ! I've been searching for a solution for this for hours.

**Comment by chriswmackey** [comment]
@ayezioro and @shahiz ,
Thanks for pointing this out.  I just fixed the bug:
https://github.com/mostaphaRoudsari/ladybug/commit/9abd3e574ad639bfdaa6a0dd1ebf2b69f5c51dc6
-Chris
