### ISSUE TITLE
"No module named OS" ERROR producing null outputs 

### ISSUE THREAD

**Issue by SebasOrozco** [mostaphaRoudsari/ladybug#394]
Hi there!
An absolute newbie here... I´m just starting to try out Ladybug on Dynamo, for preliminary environmental analysis, but came across what must be a really simple/naive mistake... I hope
For some reason I´m getting null outputs from every node when running the basic sample files.
I´ve tried several DYN/LB versions and combinations with the exact same results... All I´ve been able to track down so far is this error message by using watch nodes attached to the ERRReport outputs.

![capture](https://user-images.githubusercontent.com/29990157/27979772-b25cc37e-6335-11e7-8e9f-3132acd978a1.PNG)

This happens regardless I use my own .EPW´s, or the ones available from your download map (DOE). I even tried rebuilding the whole definition from scratch based on your tutorial videos, but still no luck...

I´m using Win7 with RVT 2016, just in case you need to know...

So, thanks in advance, hope to hear from you soon!

**Comment by chriswmackey** [comment]
@SebasOrozco ,

This github repository is for the legacy version of Ladybug that is currently used for Grasshopper.  For all issues regarding any Ladybug for Dynamo (aka. LadybugPlus), please post on this github:
https://github.com/ladybug-tools/ladybug

Also, keep in mind that LadybugPlus is in beta now so there are still bound to be issues.  Still, it would be good to have a record of this issue on that repository.

-Chris
