### ISSUE TITLE
SelectSkyMtx fails for RadiationAnalysis but works with Sky Dome

### ISSUE THREAD

**Issue by sariths** [mostaphaRoudsari/ladybug#395]
Hi @chriswmackey  and @mostaphaRoudsari,

I tried using the same skymtx for Radiation Analysis and SkyDome. The skydome works fine but radiation analysis returns an error message stating that the selectSkyMtx could not collect data(see below). Is this a bug?

![2017-07-14 13_48_06-untitled - rhinoceros 5 0 commercial - perspective](https://user-images.githubusercontent.com/10361848/28226261-1b40d5be-689b-11e7-96b0-8ca0b872d0ad.png)

I am attaching the gh file shown in the example below. https://www.dropbox.com/s/r1izj9c5tnqygas/radiationMtxTest.gh?dl=0

**Comment by chriswmackey** [comment]
@sariths ,
Sorry for the incredibly late reply on this one.  Your file seems to be running fine on my machine (even without updating the components):
![image](https://user-images.githubusercontent.com/5567574/29547534-6f18a036-86c8-11e7-926b-f12535aa47e9.png)

Do you still have the issue on your end?

**Comment by sariths** [comment]
Hi @chriswmackey , my colleague and I were using some inhouse C# scripts that appeared to be causing the problem. I can confirm that neither of us are facing this issue at the moment.
