### ISSUE TITLE
Ladybug_Monthly Bar Chart issue on 20.7.2017 update

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#396]
Hi @chriswmackey and @devngc ,
Today's update of the Ladybug_Monthly Bar Chart has an issue when basePoint point supplied and comfortModel is 0. It says:
> Runtime error (TypeErrorException): iteration over non-sequence of type NoneType
> Traceback:
>   line 1152, in main, "<string>"
>   line 1202, in script
> 
And it occurs because the variable comfortLegend is None.
I suggest to fix in line 1152 as: 
        if comfortLegend != None:
            for geo in comfortLegend: geo.Transform(moveTransform)
Then it works fine.

I'll also add that can't get why, but i'm connecting air or operative temperature to the inputData. When choosing adaptive comfort as the comfortModel input it complains/warns that:
> 1. To use the adaptive comfortModel_, one of the connected _inputData must be a temperature value.

Other comfort models work fine.
Thanks,
-A.

**Comment by devngc** [comment]
@ayezioro,

Thank you for the review! 

1. I have added a patch #397 to address error you pointed out to.
2. Concerning the adaptive comfort model: It is an original / planned behavior of this component. With the adaptive comfort model, it is assumed that the occupants tend to adjust to average outdoor air temperature. I believe that is the reason why @chriswmackey  enforces the use of dry-bulb temperature for the adaptive comfort polygon.

Thank you!
-Devang

**Comment by ayezioro** [comment]
Thanks @devngc,
As for the temperatures, i understand what you say. I'm trying to connect the dryBulbTemp from the importEPW and the operative temperatures from the simulation and then i get a severe error:

> Runtime error (ValueErrorException): invalid literal for float(): Tel Aviv-Bet Dagan - ISR MSI 
> Traceback:
>   line 132, in checkTheInputs, "<string>"
>   line 1193, in script
> 

Weird. I'm pretty sure i did something like this before.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
I have merged in @devngc's commit and let me know if your error still persists with the new component. @devngc's description of how the component works is correct and I believe that I have also connected similar cases before. If you still experience the issue, upload an example file and I can investigate.

**Comment by ayezioro** [comment]
Thanks @chriswmackey,
I get it work but somethings on the behaviour of the comfort zone is not clear.
See this example:
https://www.dropbox.com/s/pmayrzoq9warulj/BarChartVSTemperatures.gh?dl=0

If the assumption is that the dryBulbTemp is the one that sets the comfort zone, then when i connect results 2 the zone remains in place, but connecting results 3 make the zone to jump up. The results 2 and 3 are pretty much the same, so i can get why this jump happens.
Please try enabling/disabling either of the results.
I'm sure i'm missing something here, that i thought i have clear before.
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Sorry for the late reply and thanks for the example file that clearly re-creates the issue.
It turns out that you found an old bug in the part of the code that identifies the outdoor air temperature in order to calculate the adaptive comfort range.  I have just fixed it:
https://github.com/mostaphaRoudsari/ladybug/commit/77d770e6fcc4e35216683ff9a376b768ee29a64c
And you can find your example working correctly here:
https://www.dropbox.com/s/empqhmbrjpj67gu/BarChartVSTemperatures_CWM.gh?dl=0
Thanks again for finding this!
-Chris

**Comment by ayezioro** [comment]
Thanks @chriswmackey!!
-A.
