### ISSUE TITLE
EPW+STAT  - URL and file names inconsistencies

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#398]
Hi,
Downloaded a zip file from onebuilding. The thing is that the folder name where the files were unzipped is different tan the weather files names. As a result the epw and stat output are giving Null results.
I can change the file names or the zip files to be consistent, but maybe there is another option?

If you are curious about the case, the link is [this one](http://climate.onebuilding.org/WMO_Region_6_Europe/ISR_Israel/TA_Tel-Aviv/ISR_TA_Tel.Aviv-Ben.Gurion.Intl.AP.401790_IMS.zip). The folder name after unzipping is TA_Tel-Aviv.

Thanks,
-A.

**Comment by ayezioro** [comment]
Hi,
I suggest to change the code at line 76, to be:
        if _weatherFileURL and (_weatherFileURL.startswith('https://') or _weatherFileURL.startswith('http://')):
            if _weatherFileURL.endswith('.zip') or _weatherFileURL.endswith('.ZIP') or _weatherFileURL.endswith('.Zip'):
                folderName = _weatherFileURL.split('/')[-1][:-4]
            else:
                folderName = _weatherFileURL.split('/')[-2]
Which seems to be working fine for both cases (E+ and onebuilding files).
-A.

**Comment by Sonderwoods** [comment]
![capture](https://user-images.githubusercontent.com/19936679/28817347-341bc88a-76a8-11e7-9e2d-7dd8359518c3.PNG)

Not sure if same issue, but in the update an extra slash has been added (by mistake?)

**Comment by ayezioro** [comment]
Is not the same issue @Sonderwoods .
I'm talking about weather files downloaded from onebuilding. The truth is that i'm not sure the issue is for all files from that source. The specific one is from this link:
http://climate.onebuilding.org/WMO_Region_6_Europe/ISR_Israel/TA_Tel-Aviv/ISR_TA_Tel.Aviv-Ben.Gurion.Intl.AP.401790_IMS.zip
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Thanks for finding this. I'll try to fix the bug later today.

@sonderwoods ,
Your issue seems to result from inputting a URL with '\\' instead of '\'. I can put in a check that strips this extra character out but I'm pretty sure that the output will be corrected now if you correct your input.

-Chris

**Comment by chriswmackey** [comment]
@ayezioro ,

Your proposed fix was working well and it has been implemented:
https://github.com/mostaphaRoudsari/ladybug/commit/24a65208f6c01685ba4814f0932bb465f998debb
For future reference, this post would have been a good use of github's "insert code" functionality like so:
```
if _weatherFileURL and (_weatherFileURL.startswith('https://') or _weatherFileURL.startswith('http://')):
if _weatherFileURL.endswith('.zip') or _weatherFileURL.endswith('.ZIP') or _weatherFileURL.endswith('.Zip'):
folderName = _weatherFileURL.split('/')[-1][:-4]
else:
folderName = _weatherFileURL.split('/')[-2]
```

@Sonderwoods , I also took out the unnecessary backslashes after I realized that this was affecting all EPW files:
https://github.com/mostaphaRoudsari/ladybug/commit/77399d2b1c07cfb792107f72f61ed8ae30fcefea

Thanks again!

**Comment by ayezioro** [comment]
Thanks @chriswmackey  and sorry for the insert code thing :-(
-A..

**Comment by chriswmackey** [comment]
No need to apologize.  I just found it really useful in my own posts and wanted to pass it along!
