### ISSUE TITLE
LB analysis period

### ISSUE THREAD

**Issue by frank984** [mostaphaRoudsari/ladybug#408]
Please consider this topic: 
[http://www.grasshopper3d.com/group/ladybug/forum/topics/lb-analysis-period](url)

**Comment by devngc** [comment]
Hi @frank984,
The link does not work. Can you please share a working link?

**Comment by frank984** [comment]
It works for me. Please, copy and paste it in the url box.
![cattura5](https://user-images.githubusercontent.com/6491927/30161841-93c8e0dc-93d2-11e7-8a77-d5f1677bc302.JPG)

**Comment by chriswmackey** [comment]
@frank984 ,
I think we have addressed everything about your issue on the GH forum so I'm going to close this one out now.
