### ISSUE TITLE
Add Passive Solar Heating to Psychrometric Chart Strategies

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/ladybug#412]
I agree that this one should be here and I can imagine a good polygon if the user connects up the "globalHorizontalRadiation" to the annualHourlyData.

See more on this discussion here:
http://www.grasshopper3d.com/group/ladybug/forum/topics/psychart-error?commentId=2985220%3AComment%3A1801571&xg_source=msg_com_gr_forum

**Comment by chriswmackey** [comment]
This is done!

**Comment by goozgool** [comment]
I tried that, but it gives me an error
