### ISSUE TITLE
Data in Seasonal Wind Rose is off-the-charts 

### ISSUE THREAD

**Issue by alinabrouwer** [mostaphaRoudsari/ladybug#413]
Hi everyone, 

I'm having an issue with the data on a seasonal wind rose set. 
I plotted each season using analysis period based on equinox and solstice dates. 
I included a conditional statement to limit data to a>1 and a<10. 
In an attempt to make the very tiny data in the chart visible, I modified the maxFrequency to 1% (10) but this creates a situation where all the data is off the charts... 
How do I fix this? Is it a scale issue or a data resolution issue? In other words, will some of the data always remain tiny since it's composed of small values? 

Thanks!
-A

![capture](https://user-images.githubusercontent.com/20251921/30005517-2f3d3618-90b2-11e7-9cd9-51425f309830.PNG)
![capture2](https://user-images.githubusercontent.com/20251921/30005518-312f8d86-90b2-11e7-85c9-ac901571c767.PNG)

**Comment by mostaphaRoudsari** [comment]
If you want the size to be adjusted automatically based on the data leave maxFrequency input empty, otherwise you need to adjust the maxFrequency input.
