### ISSUE TITLE
Suggestion: Mesh2Hatch with layer name input

### ISSUE THREAD

**Issue by nildan** [mostaphaRoudsari/ladybug#414]
Hi!
I want to bake mesh results to a specific layer in Rhino. Right now, I can use Mesh2Hatch but I need to modify the code to have this functionality. That works, but I would love to have it as a built-in function in Ladybug.

Cheers,
Daniel

**Comment by chriswmackey** [comment]
@nildan ,
I agree this is very useful to have on the component. If you have already added it by editing the code, you can send us a pull request and we will merge it into the code base. Then you can count yourself as a Ladybug contributor.
I think Mostapha's developer playlist covers much of this process:
https://youtu.be/n_m5PDqv5pU
Otherwise, I'll get around to adding this capability eventually.

**Comment by devngc** [comment]
@nildan ,
Are you asking for [this](https://github.com/devngc/Work-in-Progress/blob/master/mesh2Hatch/mesh2Hatch.gh)? or do you wish to select from a list of active layers in Rhino and then select one of the layer names?

**Comment by nildan** [comment]
@devngc,
Exactly like that! Plus a possibility to write to sub layers (mainlayer::sublayer). I did that by using "...LayerTable.Find**ByFullPath**". Maybe both options should be available, I'm not sure.

**Comment by devngc** [comment]
@nildan,
Please correct me if I am wrong. I believe you are suggesting to have a list of child layers in case there are multiple meshes that you would like to bake to hatches on separate child layers.

**Comment by nildan** [comment]
Sorry for being unclear. I meant that I want to be able to bake to a specific sublayer in Rhino – see [this picture](https://www.dropbox.com/s/4x5xu4a63617dnb/Sk%C3%A4rmklipp.PNG?dl=0). In that case, "layer 1::layer 2" could be used to reference the sublayer.

As an example, in the Human plugin the component can be set to "Layer name only" or "Layer full path".

Thanks for helping out :-)

**Comment by chriswmackey** [comment]
@nildan ,
I was originally planning to add an input for layerName on the mesh2Hatch component (much like the Recolor mesh component - https://mostapharoudsari.gitbooks.io/ladybug-primer/content/text/components/Recolor_Mesh.html). A sublayer input also sounds good. 

@devangc ,
The ability to select the current Rhino model layers from a list seems less critical as long as the mesh2Hatch component either bakes on to an existing layer name (if the name matches) or creates a new layer.
The placing of different hatch groups on different sublayers also seems to be a bit beyond capability than most people need.
Just implementing something similar to the recolor mesh seems sufficient for now.

**Comment by devngc** [comment]
Thanks for taking care of this @Vyrwn!

**Comment by chriswmackey** [comment]
Yes, thanks for adding this in, @vyrwn!
