### ISSUE TITLE
Ladybug_SunPath angles

### ISSUE THREAD

**Issue by Vyrwn** [mostaphaRoudsari/ladybug#422]
@chriswmackey, 
in my opinion we should include the stereographic projection on the reverse angle inside ladybug ladybug.
![image](https://user-images.githubusercontent.com/10517740/32274921-2b4ead66-bf01-11e7-998b-bb8b32625478.png)

otherwise the angles do not appear correct on the stereographic projection. So in the end it will look like this.

![image](https://user-images.githubusercontent.com/10517740/32274957-5619fd84-bf01-11e7-991c-b925ec29f967.png)

I also added the "°" in the code but this is personal view. 

Let me know if you agree on the above so I can push it.

**Comment by chriswmackey** [comment]
@Vyrwn ,
Good catch.  The angles should match with the other projection.  Feel free to send a pull request with this and I will merge it in.  Or did you already fix this here:
https://github.com/mostaphaRoudsari/ladybug/pull/423/files#diff-b9af826a74ec3aa0ea71038078755d9cL3094
?

**Comment by Vyrwn** [comment]
@chriswmackey ,
yes this was already included in the pull request. I did not add the ° symbol though.

**Comment by chriswmackey** [comment]
I forgot to close this one out.  Thanks for fixing this @Vyrwn !
