### ISSUE TITLE
BakeIt not baking everything in wind rose and more ...

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#425]
Hi,
@devngc i know this is one of your babies, so here i go ...
I've found that some items are not baked when using the WindRose and WindBoundaryProfile components.
WindRose is not baking the Frequency and AverageVelocity values.
WindBoundaryProfile bakes partially and what is baked belongs to the active layer (no LB special layers defined).
There are also some elements missing: All the texts (legend, title, scale numbers, heights) and the arrows of the X/Y axes.
If no one respond here, i'll try to take care of this ... at some point.
Thanks,
-A.

**Comment by devngc** [comment]
@ayezioro,
Thank you for reporting. I will definitely take care of this.

**Comment by chriswmackey** [comment]
@devngc ,
Have you gotten the chance to check this yet?  I can also try to fix it as the creator of the last person who edited the bakeIt function.

**Comment by chriswmackey** [comment]
Ah. I see that you fixed it here:
https://github.com/mostaphaRoudsari/ladybug/pull/427

Sorry for not realizing this and thank you @devngc !

**Comment by ayezioro** [comment]
Thank yoy @devngc 
-A.

**Comment by devngc** [comment]
Thank you both for the opportunity!
