### ISSUE TITLE
non default install path 

### ISSUE THREAD

**Issue by wta12** [mostaphaRoudsari/ladybug#426]
Hi,
 in case i had radiance/daysim/OpenStudio installed in other locations than C:\ how to set path in Grasshopper ?

**Comment by mostaphaRoudsari** [comment]
@wta12, This is a honeybee question and should be posted to [honeybee repository](https://github.com/mostaphaRoudsari/honeybee/issues/).

If the path is added to System path then Honeybee should be able to find them, at least for Radiance. For Daysim we don't handle custom path as it can end up being tricky.

I close this issue and you can open a new one under honeybee repository and we can discuss the options.
