### ISSUE TITLE
typical Hot/Cold Week outputs missing from importSTAT

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#428]
Hi,
I noticed that those 2 outputs are missing from the current version of the importSTAT component.
Since i'm using it, i suppose others too.
The calculation is in the code, is just the output items that are missing.
Can it be restored?
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Yes it can be restored and I was waiting to see if someone would bring this up. The new component has so many outputs that I was testing to see if I could take out some under-utilized ones. If you are saying that you use it, I will add it back and explore some other ways of getting consolidating the component outputs. I'll post back here once I have restored the output.

**Comment by chriswmackey** [comment]
@ayezioro ,
This has been put back:
https://github.com/mostaphaRoudsari/ladybug/commit/d644a62ffaf5b5d6debe18899ba55af62d9e2b8b

I realized that there were a lot of ways to consolidate the outputs of the component, including moving the description of the climate zone to the readMe, getting rid of the dividers, and getting rid of the cooling design day range, which presently has no use in any of the components.

**Comment by ayezioro** [comment]
Thanks @chriswmackey
