### ISSUE TITLE
legendpar color input errors

### ISSUE THREAD

**Issue by Ssadaba** [mostaphaRoudsari/ladybug#441]
Legendpar requires a minimum 2 color inputs. However, every time I try to add a 2 swatch with a color keeps disconnecting the previous color input. Does anyone know what is the reason? I cannot change colors?

**Comment by mostaphaRoudsari** [comment]
You need to hold down the shift to connect multiple wires to a single input.

This question should be posted to forum: http://discourse.ladybug.tools

**Comment by Ssadaba** [comment]
Thanks Mostapha. I had my doubts whether that forum was the best to put my entry level query.

Again really appreciated.

Sergio Sádaba PE, CEng MCIBSE
Principal, Mechanical

Direct: 206-667-0575
Mobile: 206-485-5705

Stantec Consulting Services Inc.
400 Fairview Avenue North Suite 620
Seattle WA 98109-5371 US

<http://www.stantec.com>[Stantec]<http://www.stantec.com/><http://www.stantec.com>



The content of this email is the confidential property of Stantec and should not be copied, modified, retransmitted, or used for any purpose except with Stantec's written authorization. If you are not the intended recipient, please delete all copies and notify us immediately.
