### ISSUE TITLE
Location output: importEPW vs importLoc

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#446]
Hi,
I've found today a difference in the way both components give the location output.

![capture](https://user-images.githubusercontent.com/7526023/42390278-0a4a01ae-8154-11e8-967b-4ddfbcad8593.JPG)
When you use the output of the importLoc to the sunPath you get the following error:

> 1. Solution exception:need more than 5 values to unpack

I noticed that this component is using the LadybugPlus library. As a matter of fact this component is the same of the LadybugPlus.

FYI.

Thanks,
-A.

**Comment by ayezioro** [comment]
Thanks @chriswmackey,
You are right. I can't explain how it happens since i'm sure i was in the Ladybug tab picking the component. Checking now i see that the component is fine.
Sorry for the bother.
-A.

**Comment by chriswmackey** [comment]
No worries. Glad it was that simple to fix :)
