### ISSUE TITLE
Potential Bug

### ISSUE THREAD

**Issue by annasong20** [mostaphaRoudsari/ladybug#447]
Hi,

I’ve been looking through the code for Ladybug_Ladybug, and in its Preparation class, in the epwLocation method, should the second to last line of the method reading epwfile.close actually read epwfile.close()?

Thanks!

**Comment by chriswmackey** [comment]
Good catch @annasong20 !  Thank you for reporting it.

I just pushed the fix:
https://github.com/mostaphaRoudsari/ladybug/commit/43c1f5a235d2675db9fc54bd82ae62373ae0a48e

Thanks again!
