### ISSUE TITLE
ladybug is not working

### ISSUE THREAD

**Issue by tashi11** [mostaphaRoudsari/ladybug#449]
i am using rhino 6.  its showing 1. Solution exception:Method not found: 'Void Microsoft.Scripting.Utils.ExceptionUtils.RemoveData(System.Exception, System.Object)'.

how can i correct it?
![1](https://user-images.githubusercontent.com/43439410/45813168-81760080-bcef-11e8-8d47-0a40fb438ad9.PNG)

**Comment by mostaphaRoudsari** [comment]
This has been asked before. See here:

https://discourse.ladybug.tools/t/rhino-6-error-in-ladybug-and-dragonfly-components-method-exception/3188
