### ISSUE TITLE
Data conversion failed from Goo to Plane

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#455]
Hi @mostaphaRoudsari  and @chriswmackey,
I want to ask for your help to solve this issue.
Since R6 it started to show in the SunShades_Calc component. See [this discussion](https://discourse.ladybug.tools/t/possible-bug-on-sunshade-calculator-nov-20-2018-0-067/4695/2).

Two warning errors are issued:

> 1. Convex Hull: input 2 plane. error: Data conversion failed from Goo to Plane
> 2. Convex Hull: solver component. error: Data conversion failed from Goo to Plane
> 

Which are not pointing to an specific line in the code. The component produces the geometry, but still i can get how to solve the issue. I suspect it happens when the convexHullPlane variable is calculated.
Can't find in previous discussions a solution for that. I know i can ask in the GH discourse, but decided to ask here first.

Any ideas?

Thanks,
-A.

**Comment by ayezioro** [comment]
Hi again, @mostaphaRoudsari  and @chriswmackey,
The issue was solved as you can see in the discussion mentioned above.
Soon i will sync the updated version on the github.
-A.

**Comment by chriswmackey** [comment]
Thank you for letting us know, @ayezioro . Looking forward to a future pull request!
