### ISSUE TITLE
Epw file - Tokyo 476620 - wind only 180° direction

### ISSUE THREAD

**Issue by badio93** [mostaphaRoudsari/ladybug#456]
Hello everyone! 
I'm relatively a Ladybug newbie, so sorry if might seem a fool question, but i really need to solve this problem...
I'm working on an architectural project for Tokyo, specifically investigating wind direction and speed on site. I managed to work with LB wind rose and wind profile components, but i don't understand why the Tokyo epw file downloaded from Onebuilding (meteo station 476620) displays the wind like it comes from 180° degrees (south) for every hour in every day of the year! Looks like it is actually an inherent problem of this specific epw data, because using Tokyo- Hyakuri, epw data, produces a realistic wind rose instead.

I know i just could use the tokyo hyakuri file, but the actual distance of Hyakuri aeroportual meteo station from Tokyo area seems really too much for a realistic analysis! (100 km north from Tokyo, more or less).

Any hint on the origin of this probably "corrupted" wind direction values?
Found the same .epw file at 40 $ downloadable on this site http://weather.whiteboxtechnologies.com/IWEC2
Think would be worth buying the file elsewhere? Maybe data is corrupted only for onebuilding portal?

Thanks so much in advance

**Comment by mostaphaRoudsari** [comment]
Hi @badio93, This is not the right place to post this question. You should use the forum: discourse.ladybug.tools

**Comment by badio93** [comment]
Done, thank you!
