### ISSUE TITLE
dragonfly_UWGBldgTypes

### ISSUE THREAD

**Issue by sercrp** [mostaphaRoudsari/ladybug#497]
Runtime error (KeyNotFoundException): dragonfly_UWGBldgTypes

Traceback:
  line 1012, in __init__, "<string>"
  line 1063, in from_geometry, "<string>"
  line 71, in script

There is error like that.

**Comment by sercrp** [comment]
I am Architect. I want to use your urban heat island model to produce some data. But I guess I have to use grasshoper and python together. But I don't know how can I use python. Can you explain basically what steps I should follow? step by step. As I said, since I'm an architect, I don't know the code part of the job. So I can't use the model.

**Comment by mostaphaRoudsari** [comment]
Hi @sercrp, Thank you for opening an issue. You should post this question to the forum: https://discourse.ladybug.tools/

Also, you should probably use the LBT plugins instead of the legacy ones.

**Comment by sercrp** [comment]
![image](https://user-images.githubusercontent.com/102178591/159687659-8339c229-d10c-436b-acd2-bf5c08803655.png)
There is no define topology tools in LBT plugins. Only legacy one have it. I guess ı have to define geometry but I defined it via Rhino6. Please help me I have important conference next week and I have to do that.

**Comment by mostaphaRoudsari** [comment]
Hi @sercrp! I'm not the right person to help you. And ss I said above you should post this question to the forum and not here. Hopefully, someone on the forum can help you with your question.
