### ISSUE TITLE
Window is not displaying on Rhino 7

### ISSUE THREAD

**Issue by javier1332** [mostaphaRoudsari/ladybug#498]
I have Rhino 7 with Ladybug 1.5.0 and I tried creating a window as show in the pictures, and it does not display on Rhino, also I want to include the material for the window that I created and I saw that on older versions that is possible but not in the most recent. Any tips?
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/107697315/174317514-4f893a4f-c101-4bce-94cc-eb73bf59153e.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/107697315/174317523-8ca6e557-d374-489b-aad2-c1e2cc4b0713.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/107697315/174317534-daad89d9-c287-4c69-b6ec-73f516b55c0c.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/107697315/174317537-013c5258-3bae-4d6f-b9fc-535369d13d0a.png)

**Comment by mostaphaRoudsari** [comment]
Hi @javier1332! You should post this question to the forum: https://discourse.ladybug.tools
