### ISSUE TITLE
Can't find texture maker component

### ISSUE THREAD

**Issue by daphna-kaplan** [mostaphaRoudsari/ladybug#499]
Hey,
I installed ladybug but it seems that the texture maker component is missing, I guess it's a matter of versions?
Should I download it separately somehow? (Rhino 7 - LB 1.6)

**Comment by mostaphaRoudsari** [comment]
Hi @daphna-kaplan,

You should post this question on the forum. This is the repository for the legacy plugins.

https://discourse.ladybug.tools
