### ISSUE TITLE
Wrong units in radiation analysis component outputs description

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#62]
http://www.grasshopper3d.com/xn/detail/2985220:Comment:1073935

"The RadiationAnalysis component mentions it returns values in Wh/m2 and Wh, but the generated legend says kWh/m2. The latter seems to be right."

@chriswmackey this is actually half true. If the sky is generated for a single HOY the result will be in Wh/m2. In case of annual sky the values will be kWh/m2. I'm not sure how do we want to manage this?

**Comment by mostaphaRoudsari** [comment]
For some reason it is back! http://www.grasshopper3d.com/group/ladybug/forum/topics/one-doubt-about-radiation-data

Can you take care of this once more @chriswmackey? Thanks.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari , I take a look into it and have it taken care of for the release.  I think that we each thought that the other was going to fix the issue and neither of us ended up addressing it.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey thanks!

**Comment by chriswmackey** [comment]
Hello Everyone,
This is now fixed.  The selected sky matrices now appear in kWh.
![rad in kwh](https://cloud.githubusercontent.com/assets/5567574/5956683/57b251f2-a77e-11e4-8f63-b59c1b30c78f.PNG)

Enjoy!
-Chris
