### ISSUE TITLE
Wish - Window/door Recess component

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/ladybug#67]
A component that makes window/door recess. New regulations in Denmark results in walls up to 500mm thick, and with passive houses walls can even be 600mm! This have some impact on daylight studies (and a little on the energy studies) because of shade from the recess depth. 

With similar input as "Honeybee EP context Surfaces".

![honeybee_wish_window-door-recess-component-01](https://cloud.githubusercontent.com/assets/7299731/3480254/6cbf8688-035e-11e4-97a8-bdd6bbd708fb.JPG)

**Comment by mostaphaRoudsari** [comment]
@sariths developed a component for this which is almost ready to go. Someone needs to check the component and make sure it qualifies Ladybug/Honeybee component standards. http://www.grasshopper3d.com/group/ladybug/forum/topics/discussion-accuracy-of-daylight-simulations-with-no-wall?commentId=2985220%3AComment%3A1388667&groupId=2985220%3AGroup%3A658987
and
https://www.youtube.com/watch?v=xYvc25KT1Nw&feature=youtu.be

**Comment by sariths** [comment]
Hi @mostaphaRoudsari , are the coding standards documented somewhere ? I can keep that in mind next time when I am scripting something.

**Comment by chriswmackey** [comment]
@sariths ,
It is good timing that you ask.  We have just posted a set of graphic standards and guidelines for the components the other day:
https://github.com/mostaphaRoudsari/ladybug/blob/master/resources/Ladybug%20Grahpic%20Standards.md
If you could do some self-checking to see if your component meets these criteria, we can check everything quickly and integrate the component faster.

-Chris

**Comment by sariths** [comment]
@chriswmackey Thanks!  (And thanks again for the informative, and very entertaining, videos on E+ Energy Simulations on youtube). The guidelines answered almost all my questions. Here are a few things that I am not sure about:

* Icons: How do you guys design or obtain the icons for components? For my own scripts, I just get them from some royalty free images site. Is that fine for Honeybee/Ladybug too ? 

* Version: What should be the working version number when scripting a new component? Should it be whatever the latest Honeybee/Ladybug version is ?

* Python Assertions: I tend to use  the `assert` statement in python quite often to purposefully crash the program in case I know that the inputs/required conditions are wrong. For assertion failures is the orange "Warning" option the way to go ?

* Example and comments: Is there like a perfectly scripted component that can be a yardstick for development? Do you guys have any suggestions for commenting in scripts?

**Comment by antonszilasi** [comment]
@sariths 

1. Better to use photoshop to design the icons. See the existing icons here: https://www.dropbox.com/s/vb5kcvd2tgwb7wc/logos_Rev01.ai?dl=0
2. You need to put the date of the component and the latest HB LB version like so in the top of the code 

ghenv.Component.Name = "Honeybee_ Run Energy Simulation"
ghenv.Component.NickName = 'runEnergySimulation'
ghenv.Component.Message = 'VER 0.0.57\nOCT_05_2015'
ghenv.Component.Category = "Honeybee"
ghenv.Component.SubCategory = "09 | Energy | Energy"
#compatibleHBVersion = VER 0.0.56\nFEB_28_2015
#compatibleLBVersion = VER 0.0.59\nFEB_01_2015
ghenv.Component.AdditionalHelpFromDocStrings = "1"

3. If the component really doesn't work when the assertion fails better to go with red, you will also need to stop the component running completely. We do this with checktheinputs statement which return to nothing if assertion fails.

4. The E+ Run component is quite well scripted take a look as this as a standard to measure your component against.

**Comment by sariths** [comment]
@antonszilasi Thanks!

**Comment by antonszilasi** [comment]
@sariths you're welcome and please excuse my many spelling and grammar mistakes I wrote that reply on my phone!
