### ISSUE TITLE
add shadow study to sun-path

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#8]
Shouldn't be hard in Rhino 5. This is a good example by Luis: http://www.grasshopper3d.com/profiles/blogs/control-rhino-sun-system-from-gh-rhinocommon

**Comment by chriswmackey** [comment]
Wow, this issue is so old that it feels like it is for a different plugin :) 

Now that we have had the sunlight hours component for almost 5 years now, I think it's finally safe to close out this issue!
