### ISSUE TITLE
Ladybug "3d chart" component issue

### ISSUE THREAD

**Issue by stgeorges** [mostaphaRoudsari/ladybug#82]
Plugging in one of "selectAndAverage"'s outputs to "3d chart"'s "inputData", results in the following message:

```
Runtime error (IndexOutOfRangeException): index out of range: 29
Traceback:
  line 211, in makeChart, "<string>"
  line 465, in main, "<string>"
  line 619, in script
```

It's interesting that at "src" folder there's version: 'VER 0.0.57\nJUL_02_2014', while downloading the 3d chart.ghuser file, says it has been made on September 1st 2014.
Does this mean some discrepancy between these two?

To make it more confusing I have the version 0.0.58\nAUG_20_2014. I wonder where did I get that one?

**Comment by alvarobalderrama** [comment]
Hello Chris, 
I am doing this exercise and can't visualize in Rhyno. Can you help? Thanks
![image](https://user-images.githubusercontent.com/29236607/26845424-b8b9b3b4-4af6-11e7-9b60-87d11a5435d2.png)

**Comment by mostaphaRoudsari** [comment]
Hi @alvarobalderrama.
1. Type zea and press enter in Rhino. The geometry is most probably there but you can't see it.
2. Your units are in mm which will make everything slower. Change them to m.
3. Post your questions to the [Ladybug forum](http://www.grasshopper3d.com/group/ladybug/forum) and not GitHub.

**Comment by alvarobalderrama** [comment]
Thank you Mostapha,


I want to know where can I address to ask about a epw doc from my city, is not there and is the biggest city in Bolivia. Is it possible to make it myself somehow?


Thank you


Alvaro Balderrama
________________________________

**Comment by mostaphaRoudsari** [comment]
1. Check this [discussion on the forum](http://www.grasshopper3d.com/group/ladybug/forum/topics/faq-where-to-find-epw-weather-data).
2. Post your questions to the [Ladybug forum](http://www.grasshopper3d.com/group/ladybug/forum) and not GitHub.
