### ISSUE TITLE
How to Scale the Wind Rose Consistently

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/ladybug#83]
About the size of the 3D Chart, it seems to vary in size. I would like to export an image of the chart in the same size always, lets say 100mm x 200mm. Would that be possible instead of scaling the chart that does seems to relate to a specific size?

**Comment by chriswmackey** [comment]
Everyone,

What is the status on this issue?  Given that no one has responded to my opposition, I am inclined to close it out.  I can possibly imagine a new component in the Extra tab that automatically scales a set of geometry to the borders of a rectangle (to make it easy for you to generate custom reports where everything is on the same scale) but I am opposed to any additional inputs on the current ladybug components.

Let me know if such a rectangular scaling component would satisfy everyone.

-Chris

**Comment by chojje** [comment]
@chriswmackey Any progress on this? Just ran into this issue, would be convenient to have it solved within the wind rose component itself.

**Comment by chriswmackey** [comment]
This issue is mis-labeled and it only refers to the wind rose (not the 3D chart).  There are ways for correcting for this in GH with the max frequency component and I'll post an example shortly.

**Comment by chriswmackey** [comment]
I added an example to show how to create wind roses of a consistent scale:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Grid_of_Monthly_Wind_Roses&slide=1

Simply set the maxFrequency to a given number and this will ensure that all roses are the same size
