### ISSUE TITLE
Get Shadow Study out of WIP

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#92]
Suggestion by Francesco De Luca - I am copying this email here so it doesn't die in my email. This discussion needed to be broken down into multiple issues. Looks like useful components. I will upload the example files once he gives me permission.

1 - After having calculated the sun rays with LaduBug_SunPath I built a module (module 1) to determine the sun rays that actually hit the specific facade in the period and time range indicated (all the year every day between 9 and 17). A component that perform this operation would be very useful with the possibility to chose the angle, I used 90° but it could be also different, actually 90° is too large maybe, in the real project I used 85°. The purposes to develop this tool on one side is that to use only the specific rays to found the shadows of an object or a series of objects on a facade but also to find useful information and data like total hours of direct sun light on the specific facade per month (module 2) and per day per month (modules 3 and 3b).

2 - It would be very useful a component in LadyBug that make the calculation (division) of the number of direct sun light on the specific facade per month. This is important to create monthly shading performance analysis. As you can see I calculate this with a trick using the outcome of the LadyBug_SunPath  sunPositionInfo and I separate all the string with the different month name.
So I can make monthly analysis performance using the monthly hours to partition the list of the shadows ratio in module 4. In the GH file you can understand how I calculated the ratio of the shadows in comparison with the facade area.

3 - The same component that divide the total number of rays hitting a specific facade per month can have an outcome also per day of the analyzed period. I achieved this in module 3 and 3b (it is explained the difference in them. With the outcome of module 3 it is interesting to generate an excel file that shows the hours of direct sun light on the specific facade in the period and timeframe used. I send you two files I generated with the very good tool TT Toolbox to export Excel files. Do you have it? I guess yes!! :) One very strange in this report is that it looks like that there are more direct sunlight hours on the facade in March than in June!!! You ca see an explanation of this in the red panel text. Can you have a clue why? Another question about the LadyBug_SunPath in general is do the tool consider the daylight saving time? Because things changes when you make analysis that cover the entire year.

4 - With this module I calculate the performances of the shading device (different version of it are possible also) calculating the ratio between the area of the shadows every single sun ray and the area of the facade (for this example I send you is only a portion of the facades). 
The shadows are calculated using the Mesh Shadow component. Do you still have it? Once I sent you if you need to make the definition work I send you again. This works better than LadyBug Shadow_Study because what are needed are only the shadows projected on the facade and not also those on the different shading devices on themselves. So this is also another implementation you could do, that is to say a component that calculate only the shadows projected on one object or plane (a facade) or you could add this as an option to the already existing LaduBug_Shadow Study.
The difficult thing here in module 4 for the calculation of shadows ratio comes for the behavior of the Region Intersection component, it destroys the Tree structure that comes out from the Mesh Shadows component. Another difficult thing to deal with is the fact that when you use a shading device made of multiple elements (lamellas or fins) it is possible that the shadows of some of these goes out of the facade so it will result in an invalid branch in the Tree of the Region Intersection component so it is necessary to rebuild the Tree structure and replace the null or invalid Branches with Branches with area zero. You can see how I did in the module REBUILD CORRECT SHADOWS TREE of Module 4 with the explanation in yellow.
So in general would be very useful to have a component that calculates this shadows/facade ratio yearly, monthly or even daily, using the chose Analysis Period.

**Comment by chriswmackey** [comment]
To summarize the state of this issue:
1 - This has already been addressed with @mostaphaRoudsari 's component and other types of post-processing that you can do to the data.
2 - Has also been addressed with the same component.
3 - Daylight savngs time refers to [this issue.](https://github.com/mostaphaRoudsari/ladybug/issues/118)
4- I am having a hard time understanding what exactly is being discussed without the referenced example file.  Suffice it to say, the Shade Study component is being referenced and I would agree that this component needs some love in order to be really useful and taken out of WIP.  

So I'm changing the title of this issue to refer to the shadow study component.

**Comment by mostaphaRoudsari** [comment]
I think we can close this issue for now as most of them are addressed and the rest are not critical and will be implemented in the [+] libraries.
