### ISSUE TITLE
Feedback "Monthly Bar Chart"

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/ladybug#99]
@chriswmackey nice work!
I have just tested the chart, and I found some smaller bugs:
1) When changing the yScale the comfort band did not follow
2) The stackValue dont work. I suppose it should split in different charts related to number of data inputs?
3) A aesthetic wish. I would like to have the legend moved up so it is aligned with the bottom of the chart frame/line (I also would like to have this for the 3D Chart)
4) Why is it not possible to change the color of the comfort band if I use a Preview component?
5) Really good idea to write how many units the width and height is. I also discovered that in the 3D Chart, is that a new thing?

**Comment by DIXZONZY** [comment]
Hi Chris, I have been unable to use a single ladybug bar chart component to plot different data on different charts so far. The data is not flattened and is input as 2 separate lists, but it still just plots it all onto one graph, rather than 2 separate graphs.

**Comment by chriswmackey** [comment]
Sorry for the late reply @DIXZONZY but a question like this is better for our forum:
https://discourse.ladybug.tools/

You need to plug in several basePoints for the chart to not have them plot on top of each other and you'll find similar issues related to this on the forum.
